### PR TITLE
Issue 2155

### PR DESCRIPTION
**Pull request by shaomeng**
This PR addresses issue #2155.

Note: this PR should be merged after PR #2385 is merged.

### CODE REVIEW

**Comment by shaomeng** [comment]
This branch is not able to be fixed with too many conflicts.

**Comment by shaomeng** [comment]
Well, the conflicts are actually fixed. Now converting to a normal PR.

**Review by clyne — APPROVED** [review]

**Review by sgpearse — APPROVED** [review]
I think this is resolving the reported issue.  However I think this might be uncovering an unexpected use case that we haven't tested before. 

Changing the number of <none> variables seems to affect the gridded seed distribution.  I think this bug lies outside of this PR, which is only addressing a warning.  I can file another bug report and maybe we can fix that if we feel like it.

To reproduce:

1. Load our current DUKU VDC and create a Flow renderer
2. In the Seeding tab, reduce the Integration Steps to 10
3. Enable the renderer and note the 3x3x3 grid of seeds (we should see 5x5x5?)
4. In the Variables tab, set the V and W variables to <none>
5. Note that we now see a 5x3x4 grid of seeds (we should see 5x5x5?).

**Comment by clyne** [comment]
> I think this is resolving the reported issue. However I think this might be uncovering an unexpected use case that we haven't tested before.
> 
> Changing the number of variables seems to affect the gridded seed distribution. I think this bug lies outside of this PR, which is only addressing a warning. I can file another bug report and maybe we can fix that if we feel like it.
> 
> To reproduce:
> 
> 1. Load our current DUKU VDC and create a Flow renderer
> 2. In the Seeding tab, reduce the Integration Steps to 10
> 3. Enable the renderer and note the 3x3x3 grid of seeds (we should see 5x5x5?)
> 4. In the Variables tab, set the V and W variables to
> 5. Note that we now see a 5x3x4 grid of seeds (we should see 5x5x5?).

@sgpearse I agree that this is probably outside of this PR, but please do submit a bug report. Thanks!

**Pull request merged**
