### PR TITLE
Fix #1509 VFileSlector: more intelligent space and layout management

### LINKED ISSUE #265: ImageRenderer: Current image file display
I believe we should be displaying the current filename of our Image renderer without its directory path.

To reproduce:
1) Spin up Vapor with KatrinaMaster.nc
2) Create an Image renderer
3) In the Appearance tab, it's a little bit hard to ascertain our current image file

### LINKED ISSUE #1509: VFileSlector: more intelligent space and layout management
**Describe the bug**
The current composite widget `VFileSelector` doesn't seem to be very intelligent in managing spaces/layouts. This is not ideal, since a key promise of these rebranded `VaporWidgets` is to manage layout/spaces intelligently. Without such capability, the benefit of `VaporWidgets` is in doubt. 

**To Reproduce**
1. Checkout a branch that makes use of `VFileSelector`. In this report I'd use `flow`.
2. Create a flow renderer.
3. Switch to `Seeding` tab, and select a file at the bottom.
4. Notice the layout of the `VFileSelector` in the screenshot. There's much white space between the label and the button, while not enough space to display the full name of the file in the text box.
5. A more intelligent layout manager would give enough space for the text box to display the full filename when there's still white space left. 

**Screenshots**
Screenshot 2019-04-22 17 25 38

### PR DESCRIPTION
**Pull request by StasJ**
Fix #1509
Fix #265

### CODE REVIEW

**Comment by clyne** [comment]
@sgpearse our builds seem to be failing

**Comment by sgpearse** [comment]
@StasJ In #265, I suggest that we remove the directory path and only display the file name.  I'm not sure what the consensus was on this, but I think that would be ideal.  Especially since the user can't type a path into the line edit.

If there's a reason not to do that, a tool-tip with the file path would allow us to show the full path without having to scroll through the text with our mouse.

**Review by sgpearse — CHANGES_REQUESTED** [review]
Please see my comment above.

**Comment by clyne** [comment]
Consider right-justifying the text or only showing the file name and having path in tooltip

**Comment by sgpearse** [comment]
FYI - the Circle tests are passing on this PR after merging with 'main'.  I've submitted PR (#2606) to be incorporated here for convenience, but feel free to just merge on your own branch.

**Comment by StasJ** [comment]
> Stas, could you provide a brief textual description on what's changed? E.g., is the widget rewritten or just a tab was rewritten? Is it a new policy thing or a new self-adjusting scheme was introduced? Or any other summary of the changes.

This PR only has 3-4 lines of changes. @sgpearse it seems the master rename messed up the diffs.

**Comment by clyne** [comment]
@stasj needs to resubmit to resolve issue with 26 files change from transition from master to main.

**Review by shaomeng — APPROVED** [review]

**Review by sgpearse — APPROVED** [review]

**Pull request merged**
