### PR TITLE
Issue2645 Fix poor barb performance with large datasets

### LINKED ISSUE #2645: Performance of Barbs unusable with larger data
### Describe the bug
The Barb renderer is unusable with larger data. It appears to be performing unnecessary calculations with every update, including scene navigation.

### To Reproduce
1. Load PALM/cbl_KIT_ug00_dx10_masked_M01.000.0119.split.nc from glade
2. Enable the barb renderer
3. Try to change the viewpoint. It's impossible to do this interactively.

### PR DESCRIPTION
**Pull request by StasJ**
Fixes the problem by caching the generated barbs.

Fix #2645

### CODE REVIEW

**Comment by sgpearse** [comment]
@stasj could we please remove the commented code in BarbRenderer::_isCacheDirty()?

**Comment by sgpearse** [comment]
> That code was left intentionally but if you insist.

I don't want to fuss, but this is in our [convention doc](https://github.com/NCAR/VAPOR/wiki/Notions-And-Actions-on-Code-Quality).  We can change the doc too.  I'd just like to be on the same page if we use a standard.

**Review by clyne — APPROVED** [review]
Nice work! But please remove commented out code.

**Review by shaomeng — APPROVED** [review]

**Review by sgpearse — APPROVED** [review]
Thank you stas.

**Pull request merged**
