### PR TITLE
Issue 2122 - New Colormaps

### LINKED ISSUE #2122: New Color Maps based on CMOcean
Sam McClatchie has requested that we expand our library of color maps.  He recommends using the ones listed at the following website:

https://matplotlib.org/cmocean/

### PR DESCRIPTION
**Pull request by sgpearse**
Added CMOcean colormaps from matplotlib. 

Fixes #2122

https://matplotlib.org/cmocean/

### CODE REVIEW

**Comment by clyne** [comment]
Indeed. How about a 

> With this PR our colormap selector may be getting too crowded. We may want to organize these somehow.
> 
Indeed. How about a 2D matrix instead of 1D?

**Comment by StasJ** [comment]
I was thinking more along the lines of categorizing them using submenus, for example placing diverging colormaps in their own submenu.

**Comment by shaomeng** [comment]
Is there a general consensus on what are the most useful color maps, and
potentially remove the less-useful ones from our menu?

I don't think providing more options is always an improvement. ( E.g., from
5 to 10 is an improvement, while from 20 to 25 might not. )

**Comment by clyne** [comment]
That would be fine too.

> On Feb 6, 2020, at 11:53 AM, StasJ <notifications@github.com> wrote:
> 
> I was thinking more along the lines of categorizing them using submenus, for example placing diverging colormaps in their own submenu.
> 
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu

**Comment by sgpearse** [comment]
@stas We may want to consider a third column for "wave" colormaps.  These can be sequential and diverging.  However we currently only have two of them (topo.tf3 and oxy.tf3).

https://sciviscolor.org/wave-colormaps/

**Pull request closed without merging**
