### PR TITLE
Wireframe

### PR DESCRIPTION
**Pull request by clyne**
@shaomeng, @sgpearse , I've created a new renderer to display a variable's mesh as a wireframe. I did this mainly because I needed it to debug the 3D grid classes that I'm working on, but also because it's a useful feature. Per our discussion please help test this PR before I merge it. Thanks!

### CODE REVIEW

**Comment by shaomeng** [comment]
Is the resolution correct? 
In the following screenshot, the `Refinement level` menu shows "22x20x4", but the wireframes have only 3 planes. 
screenshot from 2018-06-15 17-00-31

**Comment by shaomeng** [comment]
The color mapping isn't responding to user changes. 
In the following screenshot, the color map has only 2 colors, while the frames have a good transition between 2 different colors. 

screenshot from 2018-06-15 17-01-09

**Comment by StasJ** [comment]
Can we somehow pin this commit to the wiki to have as a reference for adding renderers?

**Comment by shaomeng** [comment]
There are compiler warnings observed: 
Platform: cisl-vapor. 

/home/shaomeng/Git/VAPOR-git-src/lib/render/Renderer.cpp:591:34: warning: ‘Tuy’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   Tuy -= _textObject->getHeight();
                                  ^
/home/shaomeng/Git/VAPOR-git-src/lib/render/Renderer.cpp:592:35: warning: ‘Tlx’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   double coords[] = {Tlx, Tuy, 0.f};
  
/home/shaomeng/Git/VAPOR-git-src/lib/wasp/Compressor.cpp:824:13: warning: ‘L’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   delete [] L;
             ^

/home/shaomeng/Git/VAPOR-git-src/apps/tiff2geotiff/tiff2geotiff.cpp:259:38: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
     fscanf( tfw, "%lf", pixsize + 0 );
                                      ^
/home/shaomeng/Git/VAPOR-git-src/apps/tiff2geotiff/tiff2geotiff.cpp:260:33: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
     fscanf( tfw, "%lf", &y_rot );
                                 ^
/home/shaomeng/Git/VAPOR-git-src/apps/tiff2geotiff/tiff2geotiff.cpp:261:33: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
     fscanf( tfw, "%lf", &x_rot );
                                 ^
/home/shaomeng/Git/VAPOR-git-src/apps/tiff2geotiff/tiff2geotiff.cpp:262:38: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
     fscanf( tfw, "%lf", pixsize + 1 );
                                      ^
/home/shaomeng/Git/VAPOR-git-src/apps/tiff2geotiff/tiff2geotiff.cpp:263:32: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
     fscanf( tfw, "%lf", &xoff );
                                ^
/home/shaomeng/Git/VAPOR-git-src/apps/tiff2geotiff/tiff2geotiff.cpp:264:32: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
     fscanf( tfw, "%lf", &yoff );
                                ^

**Comment by shaomeng** [comment]
@clyne The earlier reported issues seem still there. Also, I've observed a few compiler warnings that we should address. Not sure if these warnings are introduced by this particular PR or not...

**Comment by clyne** [comment]
These warnings were not created by this branch. They’ve always been there.

jc

> On Jun 19, 2018, at 10:54 AM, Samuel Li <notifications@github.com> wrote:
> 
> There are compiler warnings observed:
> Platform: cisl-vapor.
> 
> /home/shaomeng/Git/VAPOR-git-src/lib/render/Renderer.cpp:591:34: warning: ‘Tuy’ may be used uninitialized in this function [-Wmaybe-uninitialized]
> Tuy -= _textObject->getHeight();
> ^
> /home/shaomeng/Git/VAPOR-git-src/lib/render/Renderer.cpp:592:35: warning: ‘Tlx’ may be used uninitialized in this function [-Wmaybe-uninitialized]
> double coords[] = {Tlx, Tuy, 0.f};
> 
> /home/shaomeng/Git/VAPOR-git-src/lib/wasp/Compressor.cpp:824:13: warning: ‘L’ may be used uninitialized in this function [-Wmaybe-uninitialized]
> delete [] L;
> ^
> 
> /home/shaomeng/Git/VAPOR-git-src/apps/tiff2geotiff/tiff2geotiff.cpp:259:38: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
> fscanf( tfw, "%lf", pixsize + 0 );
> ^
> /home/shaomeng/Git/VAPOR-git-src/apps/tiff2geotiff/tiff2geotiff.cpp:260:33: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
> fscanf( tfw, "%lf", &y_rot );
> ^
> /home/shaomeng/Git/VAPOR-git-src/apps/tiff2geotiff/tiff2geotiff.cpp:261:33: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
> fscanf( tfw, "%lf", &x_rot );
> ^
> /home/shaomeng/Git/VAPOR-git-src/apps/tiff2geotiff/tiff2geotiff.cpp:262:38: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
> fscanf( tfw, "%lf", pixsize + 1 );
> ^
> /home/shaomeng/Git/VAPOR-git-src/apps/tiff2geotiff/tiff2geotiff.cpp:263:32: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
> fscanf( tfw, "%lf", &xoff );
> ^
> /home/shaomeng/Git/VAPOR-git-src/apps/tiff2geotiff/tiff2geotiff.cpp:264:32: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
> fscanf( tfw, "%lf", &yoff );
> ^
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu

**Comment by clyne** [comment]
My bad. I forgot to push to the remote. Should be there now.

jc

> On Jun 19, 2018, at 10:57 AM, Samuel Li <notifications@github.com> wrote:
> 
> @clyne The earlier reported issues seem still there. Also, I've observed a few compiler warnings that we should address. Not sure if these warnings are introduced by this particular PR or not...
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu

**Comment by shaomeng** [comment]
- Question 1 and Bug 1 are resolved now.
- We need to come up with a consensus on when compiler warnings are to be addressed. I'd advocate at the time before merging to master, e.g., now.

**Comment by clyne** [comment]
> On Jun 19, 2018, at 11:39 AM, Samuel Li <notifications@github.com> wrote:
> 
> 	• Question 1 and Bug 1 are resolved now.

Good deal.

> 	• We need to come up with a consensus on when compiler warnings are to be addressed. I'd advocate at the time before merging to master, e.g., now.


I agree in the case that the compiler warnings were introduced in the PR, but in this case they were extant. Moreover, they’re not even in files modified by the PR.

jc

> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu

**Pull request merged**
