### PR TITLE
Upgrade to Qt 5.13.2 - Issue 2247

### PR DESCRIPTION
**Pull request by sgpearse**
Addresses #2247

These libraries are located in our Google Drive folder:
   [Vapor Team Drive>]/Third Party Libraries

This link may or may not work:
https://drive.google.com/drive/u/0/folders/0B0dQMtxB89M0Q2F2U3ZaQ2dVeWs

Download the new third party libraries at the links below:
[CentOS](https://drive.google.com/open?id=1e7F3kDoKctBmB3NOF4dES2395oScb9_0)
[Ubuntu](https://drive.google.com/open?id=1j4IO4VCU0Wvyu2T3BH0e9I0qiiwCIrEd)
[Darwin](https://drive.google.com/open?id=1-2e1O1lZ38GgPs-fkhNxt8l9KNuwX4C2)
[Windows](https://drive.google.com/open?id=1j4IO4VCU0Wvyu2T3BH0e9I0qiiwCIrEd)

### CODE REVIEW

**Comment by sgpearse** [comment]
> My only request is that you add a reference to the google drive files rather than direct share links so we don't have to reference this PR for the files.

I'm not sure what you mean by "add a reference to the google drive files."  Since moving away from glade, we've always kept our third party libraries in the **Third Party Libraries** directory on GDrive.

**Comment by shaomeng** [comment]
> Addresses #2247
> 
> These libraries are located in our Google Drive folder:
> [Vapor Team Drive>]/Third Party Libraries
> 
> This link may or may not work:
> https://drive.google.com/drive/u/0/folders/0B0dQMtxB89M0Q2F2U3ZaQ2dVeWs
> 
> Download the new third party libraries at the links below:
> [CentOS](https://drive.google.com/open?id=1e7F3kDoKctBmB3NOF4dES2395oScb9_0)
> [Ubuntu](https://drive.google.com/open?id=1j4IO4VCU0Wvyu2T3BH0e9I0qiiwCIrEd)
> [Darwin](https://drive.google.com/open?id=1-2e1O1lZ38GgPs-fkhNxt8l9KNuwX4C2)
> [Windows](https://drive.google.com/open?id=1j4IO4VCU0Wvyu2T3BH0e9I0qiiwCIrEd)

Scott, just to confirm, the 3rd party libraries are more like March-2020, even though they're named Aug-2019, is that right?

If so, isn't this a pretty confusing situation?

**Comment by sgpearse** [comment]
@shaomeng, as we discussed in our email thread, all libraries were built in August of 2019 with the exception of Qt.

**Comment by shaomeng** [comment]
> @shaomeng, as we discussed in our email thread, all libraries were built in August of 2019 with the exception of Qt.

Got it, thanks for confirming Scott!

**Comment by shaomeng** [comment]
When I test this PR on cisl-vapor, there are around a dozen QT related warnings. 

Though those warnings aren't specifically introduced by this PR, but given that this PR is still at a very manageable size, I'd suggest addressing them along this PR, instead of opening a new PR. @StasJ you might want to double check if there are warnings introduced by PWidgets.

**Comment by sgpearse** [comment]
@shaomeng, I see the warnings you're talking about.  Many of them are about deprecated functions in Qt.  I found and fixed only one warning regarding PWidgets, which I'm working closely with now.  I'd like to make a more comprehensive effort to eliminate warnings in the near future.

**Comment by shaomeng** [comment]
@sgpearse I built using Release configurations, maybe that gave me more warnings.

Also, isn't moving away from deprecated functions a price we already decided to pay when we upgraded QT? 

But after all I do think those warnings hardly belong to this PR, so I have no problem with this particular PR.

**Comment by clyne** [comment]
@sgpearse there are conflicts in the PR now. As soon as they are resolved we can merge.

**Comment by sgpearse** [comment]
> @sgpearse I built using Release configurations, maybe that gave me more warnings.

Let's talk about this today.  I'd be ok with fixing warnings on Ubuntu16 for this release, and enforcing a no-warning policy on PR's for only this OS.

**Pull request merged**
