### PR TITLE
Error check and dump metadata function

### PR DESCRIPTION
**Pull request by ifranda**
I thought I'd open a small PR to test run making changes to the Python api. I've made two changes:
1. When RGB colors are converted to HSV, make a check to verify the list is of length 3. I think this stops the kernel from crashing when using incorrect inputs with `SetColorRGBList`
2. Added a `DumpVarMetadata` function for datasets. Some of the examples printed out the metadata manually, and I thought it would be nice to have it integrated into the package. 

I've tested it out and I think it's working as intended, but let me know if there's anything else I should watch out for!

### CODE REVIEW

**Comment by NihanthCW** [comment]
Great! You can assign Stas as a reviewer and discuss any questions tomorrow.

**Review by StasJ — COMMENTED** [review]
Looks good, thanks! I would suggest implementing `DumpVarMetadata` as `__repr__` and include dimensions and coordinates, similar to Xarray. Also please address Circle tests.

**Comment by ifranda** [comment]
Just made the change! We can definitely talk more about what's being returned here if we have other ideas.

**Review by StasJ — APPROVED** [review]
Looks good, thanks.

**Pull request merged**
