### PR TITLE
Ospray2 gui

### PR DESCRIPTION
**Pull request by StasJ**
This PR is based off the gui refactoring PR. Once that is merged this can be retargeted at master.

OSPRay can be built conditionally with the BUILD_OSP option in CMake. The path for OSPRay is configured in the site.NCAR file. The latest release of OSPRay, v2.4.0, works out of the box.

### CODE REVIEW

**Comment by clyne** [comment]
@StasJ, how does one configure the environment to build with OSPray? I downloaded 2.4 and installed it in /Users/clyne/apps/ospray-2.4.0.x86_64.macosx. But when I set the OSPRAY target in cmake to this directory I get: 

WARNING: Target "vapor" requests linking to directory
 "/Users/clyne/apps/ospray-2.4.0.x86_64.macosx".  Targets may link only to
 libraries.  CMake is dropping the item.
 WARNING: Target "vaporpychecker" requests linking to directory
 "/Users/clyne/apps/ospray-2.4.0.x86_64.macosx".  Targets may link only to
 libraries.  CMake is dropping the item.
 WARNING: Target "render" requests linking to directory
 "/Users/clyne/apps/ospray-2.4.0.x86_64.macosx".  Targets may link only to
 libraries.  CMake is dropping the item.
 WARNING: Target "render" requests linking to directory
 "/Users/clyne/apps/ospray-2.4.0.x86_64.macosx".  Targets may link only to
 libraries.  CMake is dropping the item.

**Comment by StasJ** [comment]
> @StasJ, how does one configure the environment to build with OSPray? I downloaded 2.4 and installed it in /Users/clyne/apps/ospray-2.4.0.x86_64.macosx. But when I set the OSPRAY target in cmake to this directory I get:
> 
> WARNING: Target "vapor" requests linking to directory
> "/Users/clyne/apps/ospray-2.4.0.x86_64.macosx". Targets may link only to
> libraries. CMake is dropping the item.
> WARNING: Target "vaporpychecker" requests linking to directory
> "/Users/clyne/apps/ospray-2.4.0.x86_64.macosx". Targets may link only to
> libraries. CMake is dropping the item.
> WARNING: Target "render" requests linking to directory
> "/Users/clyne/apps/ospray-2.4.0.x86_64.macosx". Targets may link only to
> libraries. CMake is dropping the item.
> WARNING: Target "render" requests linking to directory
> "/Users/clyne/apps/ospray-2.4.0.x86_64.macosx". Targets may link only to
> libraries. CMake is dropping the item.

@clyne you should be setting `OSPRAYDIR`, not `OSPRAY` (There is a an example in the site.NCAR file for my setup)

**Comment by clyne** [comment]
@stasj the gui refactoring PR has been merged.

**Comment by StasJ** [comment]
@clyne There appears to be a problem with GitHub. When you run git diff locally, it works as expected and only shows about 3.5k insertions and 2k deletions, whereas GitHub is showing 4.4k insertions and 20k deletions.

**Comment by clyne** [comment]
@StasJ is there something you need me to do? This passes checks earlier.

**Comment by StasJ** [comment]
> @StasJ is there something you need me to do? This passes checks earlier.

GitHub was showing the wrong diff (different from when I ran the diff manually locally) so I recreated the PR in a way that github will definitely work (#2401)

**Pull request closed without merging**
