### PR TITLE
Fixed #2867 - Memory Error---test_params2

### LINKED ISSUE #2867: Memory Error---test_params2
Utility program `test_params2` has `definitely lost` memory errors:
```
==151381== LEAK SUMMARY:
==151381==    definitely lost: 104 bytes in 1 blocks
==151381==    indirectly lost: 56 bytes in 1 blocks
==151381==      possibly lost: 0 bytes in 0 blocks
==151381==    still reachable: 4,096 bytes in 1 blocks
==151381==         suppressed: 0 bytes in 0 blocks
==151381== Rerun with --leak-check=full to see details of leaked memory
```

### PR DESCRIPTION
**Pull request by clyne**
Backed out use of std::unique_ptr, which wasn't playing well with raw pointers contained in parent classes.

Fixed original memory leak, which precipitated use of smart pointers in the first place.

### CODE REVIEW

**Comment by shaomeng** [comment]
Hi John, thanks for submitting this PR, but I noticed something interesting, which is that the current `main` (b5800684adf303850b9b7e85345ad20122ac7421) and `issue_2867` branches both give zero memory errors. More specifically, the original memory leak and the later memory error that you found are both gone.

Right now, both branches give me exactly the same valgrind output as pasted below. Is it the case on your end? 
```
-bash-4.2$ valgrind ./debug_binaries/test_params2 
==146689== Memcheck, a memory error detector
==146689== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==146689== Using Valgrind-3.17.0 and LibVEX; rerun with -h for copyright info
==146689== Command: ./debug_binaries/test_params2
==146689== 
==146689== Warning: set address range perms: large range [0x136d1000, 0x24ca3000) (defined)
Viewpoint::~Viewpoint() this=0x1ffeffd100
Viewpoint::~Viewpoint() this=0x1ffeffd100
SUCCESS: vp1 == vp2
SUCCESS: vp1 != vp2
Viewpoint::~Viewpoint() this=0x267e45f0
SUCCESS: vp1 == vp2
ViewpointParams::~ViewpointParams() this=0x1ffeffd1a0
Viewpoint::~Viewpoint() this=0x267ece40
ViewpointParams::~ViewpointParams() this=0x1ffeffd1f0
Viewpoint::~Viewpoint() this=0x267eff80
Allocated note count after delete : 0
==146689== 
==146689== HEAP SUMMARY:
==146689==     in use at exit: 162,117 bytes in 130 blocks
==146689==   total heap usage: 22,093 allocs, 21,963 frees, 2,021,189 bytes allocated
==146689== 
==146689== LEAK SUMMARY:
==146689==    definitely lost: 0 bytes in 0 blocks
==146689==    indirectly lost: 0 bytes in 0 blocks
==146689==      possibly lost: 0 bytes in 0 blocks
==146689==    still reachable: 162,117 bytes in 130 blocks
==146689==                       of which reachable via heuristic:
==146689==                         stdstring          : 6,518 bytes in 57 blocks
==146689==         suppressed: 0 bytes in 0 blocks
==146689== Rerun with --leak-check=full to see details of leaked memory
==146689== 
==146689== For lists of detected and suppressed errors, rerun with: -s
==146689== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

**Comment by clyne** [comment]
@shaomeng the commit ID that I have for main is 

```
cisl-benona[1117] git rev-parse --short HEAD
b5800684a
```

not 

b5800684

In any event I get an error on main with valgrind. Moreover, the test drive will dump core:

==14685== Invalid read of size 8
==14685==    at 0x1001865A8: VAPoR::ParamsBase::~ParamsBase() (lib/params/ParamsBase.cpp:99)
==14685==    by 0x10018B174: VAPoR::ParamsSeparator::~ParamsSeparator() (include/vapor/ParamsBase.h:225)
==14685==    by 0x100189C94: VAPoR::ParamsSeparator::~ParamsSeparator() (include/vapor/ParamsBase.h:225)
==14685==    by 0x10018A9A8: VAPoR::ParamsSeparator::~ParamsSeparator() (include/vapor/ParamsBase.h:225)
==14685==    by 0x100189DEE: VAPoR::ParamsContainer::~ParamsContainer() (lib/params/ParamsBase.cpp:443)
==14685==    by 0x100189F44: VAPoR::ParamsContainer::~ParamsContainer() (lib/params/ParamsBase.cpp:437)
==14685==    by 0x100189F68: VAPoR::ParamsContainer::~ParamsContainer() (lib/params/ParamsBase.cpp:437)
==14685==    by 0x1001C1D1B: std::__1::default_delete<VAPoR::ParamsContainer>::operator()(VAPoR::ParamsContainer*) const (memory:1423)
==14685==    by 0x1001BFC5B: std::__1::unique_ptr<VAPoR::ParamsContainer, std::__1::default_delete<VAPoR::ParamsContainer> >::reset(VAPoR::ParamsContainer*) (memory:1684)
==14685==    by 0x1001C02B2: VAPoR::ViewpointParams::operator=(VAPoR::ViewpointParams const&) (lib/params/ViewpointParams.cpp:111)
==14685==    by 0x1000067A7: test() (test_apps/params2/test_params2.cpp:53)
==14685==    by 0x100006D7E: main (test_apps/params2/test_params2.cpp:94)
==14685==  Address 0x118 is not stack'd, malloc'd or (recently) free'd
==14685== 
==14685== 
==14685== Process terminating with default action of signal 11 (SIGSEGV)
==14685==  Access not within mapped region at address 0x118
==14685==    at 0x1001865A8: VAPoR::ParamsBase::~ParamsBase() (lib/params/ParamsBase.cpp:99)

**Comment by shaomeng** [comment]
@clyne  It's interesting. First the main we have are the same. git rev-parse --short HEAD gives me the same output. (If you expand them to full length the hash numbers are the same.)

Second, I only have valgrind on Casper, not my macbook because of Monterey issues. So the exact same valgrind output I reported are from Casper. (Note, I did see the same memory error you reported yesterday, very weird.)

Third, while I cannot run valgrind on my macbook, I can run the executable of test_params2. In both DEBUG or RELEASE build on main, it doesn't crash with many repeated runs. But of course it needs some luck to crash or not crash.

Maybe you can run the test on Casper and see if there is any error on main? 

Alternatively, for the sake of this PR, we can accept it and merge it, and claim that VAPOR has one less bug than yesterday.

**Comment by clyne** [comment]
> @clyne It's interesting. First the main we have are the same. git rev-parse --short HEAD gives me the same output. (If you expand them to full length the hash numbers are the same.)
> 
> Second, I only have valgrind on Casper, not my macbook because of Monterey issues. So the exact same valgrind output I reported are from Casper. (Note, I did see the same memory error you reported yesterday, very weird.)
> 
> Third, while I cannot run valgrind on my macbook, I can run the executable of test_params2. In both DEBUG or RELEASE build on main, it doesn't crash with many repeated runs. But of course it needs some luck to crash or not crash.
> 
> Maybe you can run the test on Casper and see if there is any error on main?

I thought you said above that you ran it in casper with no problem?

> 
> Alternatively, for the sake of this PR, we can accept it and merge it, and claim that VAPOR has one less bug than yesterday.

That would be my vote :-). There was an obvious bug introduced when Transforms were added to the ViewpointParams class; they were not following the same design patten that was being used elsewhere. All i did was made their use consistent with other Params classes that use ParamsContainers to manage list of parameters.

**Comment by shaomeng** [comment]
Yeah, all my valgrind tests were on Casper. I thought that you can do a sanity check in case I messed up something. 

I'm ok with merging the PR and stop investigating some weird behaviors. I'll have it approved.

**Review by shaomeng — APPROVED** [review]

**Comment by shaomeng** [comment]
@clyne One thought: if you test main on Casper, and also see zero error on Casper while see a few errors on macos, it might indicate that valgrind doesn't work on macos afterall.

**Pull request merged**
