### PR TITLE
Issue 2936

### LINKED ISSUE #2936: Changing flow color mapped var causes paths to break
1. Open `/glade/p/cisl/vast/vapor/Bugs/2936/2936.vs3`
2. Change the Color Mapped Variable

Notice that the flow paths have changed and are now incorrect.

ss

### PR DESCRIPTION
**Pull request by StasJ**
This PR fixes #2936

### CODE REVIEW

**Comment by StasJ** [comment]
Reverted merge and reopened due to failing CircleCI

**Comment by clyne** [comment]
@stasj there still seems to be a CI conflict here...

**Comment by StasJ** [comment]
@clyne yes, but this was Sam’s PR so I just reopened it since it was
accidentally merged with a CI conflict

**Review by clyne — APPROVED** [review]

**Comment by clyne** [comment]
I'm not entirely clear what's going on, but is it now OK to merge this @stasj, @shaomeng ?

**Comment by shaomeng** [comment]
> I'm not entirely clear what's going on, but is it now OK to merge this @StasJ, @shaomeng ?

I'd think so, but let's ask what @StasJ thinks.

**Comment by StasJ** [comment]
> I'm not entirely clear what's going on, but is it now OK to merge this @StasJ, @shaomeng ?

I approved the original PR based on the code review but then noticed that it failed CircleCI. Before I could undo my approval, the PR was merged. I unmerged the original PR but you cannot reopen PRs so I opened a new PR that is a duplicate of the original. It is now passing circle so it is good to merge.

**Comment by clyne** [comment]
Got it. Thanks

**Pull request merged**
