### PR TITLE
Issue 617 - Calculating Image Renderer height is very slow

### PR DESCRIPTION
**Pull request by clyne**
This PR significantly improves, but does not completely resolve the performance problems with #617. Specifically, this PR augments the API of many of the public and private Grid class methods to offer versions that use raw pointers instead of STL vectors as arguments. The latter are problematic due to the vector classes use of heap memory, which results in a performance bottleneck when called many times (e.g. inside a large loop). These changes are general and will benefit other users of the Grid class. With regard to issue #617, the resulting speedup is ~3x. 

To further improve performance specifically with regard to #617 would require changes to the ImageRenderer class to allow more intelligent sampling of the displayed image. Currently, for images displaced by a height field sampling is done in image space at the resolution of the displayed image. This should probably be so that the image sampled in the space of the height field, which would provide equivalent visual results, but require less samples.

### CODE REVIEW

**Comment by shaomeng** [comment]
John, it looks in most of the changes you've already known the size of the array to be passed in/out. In such cases, I recommend you consider using `std::array` instead of a raw pointer. (https://en.cppreference.com/w/cpp/container/array)
A few benefits of the container type over raw pointers: 
1. The length of the array is *strictly* enforced;
2. It plays well with all the STL algorithms, including the use of iterators, etc. 
3. It avoids all the pitfalls associated with the use of raw pointers.

**Comment by clyne** [comment]
You're probably right. I'll have to play around with it and see how it performs. Maybe next weekend :-)

**Comment by shaomeng** [comment]
> You're probably right. I'll have to play around with it and see how it performs. Maybe next weekend :-)

Oh, it'll be at least as fast as raw pointers. With stronger guarantees on memory bounds and overlapping and stuff like that, it'll be even faster in some cases.

**Comment by shaomeng** [comment]
> You're probably right. I'll have to play around with it and see how it performs. Maybe next weekend :-)

Oh btw, when you play around with it, remember to set up something like this to reduce your typing: 
`using coord3 = std::array<float, 3>; using coord6 = std::array<float, 6>;`

**Comment by clyne** [comment]
@StasJ , @shaomeng, I've converted most of the Grid API to use sdt::array for passing indices and coordinates. The biggest implication of this change is that std::array is a fixed length (3 elements). Many places in the code assume (wrongly) that the length of indices or coordinate vectors/arrays will match the dimensionality of the grid. To minimize the number of changes in the application I've preserved the old, slower performing std::vector interfaces. I've only migrated the application to the new std::array interface in places where performance matters. Another big todo is to refactor the Grid iterators. They are still using the std::vector interface, but in a way that typically does not impact performance. The only real motivation to address the iterators is for consistency. I think the time to address the iterators is when we address #2250

**Pull request merged**
