### PR TITLE
Issue2207

### LINKED ISSUE #2207: Collect installer and source download metrics
Verify, and if implement if needed, a mechanism for collecting VAPOR installer download metrics.

### PR DESCRIPTION
**Pull request by sgpearse**
Fixes #2207 

This adds a script that uses the GitHub API to log download metrics on our release assets.  It generates a plot showing the trend of our downloads for each OS.

This script can be run for any repository by modifying the variables located at the top.

It can also be run by CircleCI at an arbitrary frequency to collect and post the metric data.

To use:
>python /VAPOR/scripts/metrics.py

### CODE REVIEW

**Comment by clyne** [comment]
Scott, this looks great. But I’ve been running it for 20 minutes and it hasn’t returned anything. Is that expected?

thanks - jc


> On Feb 5, 2020, at 12:02 PM, sgpearse <notifications@github.com> wrote:
> 
> @sgpearse requested your review on: #2212 Issue2207.
> 
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu

**Comment by sgpearse** [comment]
It should print one of two things:

1) A message that the GitHub API request failed
2) Info on the total downloads, and a new window with a plot

The script terminates in the case of 1.  It also terminates after the plot window is closed.

If it's not reporting anything after 20 minutes, then that's not right.  But it's possible that your plot window is still open somewhere, so the script is waiting for it to close.

**Comment by clyne** [comment]
I can't find any open plot windows. The script just hangs and does not print anything.

Also, do you want the pickle file included in this PR

**Comment by sgpearse** [comment]
I think you may not be specifying which python executable to use.  I previously had the usage stated as follows:
> python /VAPOR/scripts/metrics.py

But I just went ahead and added a shebang line to specify the first python3 found in the user's path.  You can now launch it by just typing the script name.

**Comment by sgpearse** [comment]
PS - The pickle file holds all of the data for our metrics, so we can generate a time series.  GitHub's API only allows us to gather the current number of downloads, so we need to log our queries somehow.  Pickle files let us save logs and restore them later.

**Comment by clyne** [comment]
Still confused. Does the pickle file need to be in the  repo?

> On Feb 5, 2020, at 1:52 PM, sgpearse <notifications@github.com> wrote:
> 
> PS - The pickle file holds all of the data for our metrics, so we can generate a time series. GitHub's API only allows us to gather the current number of downloads, so we need to log our queries somehow. Pickle files let us save logs and restore them later.
> 
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu

**Pull request closed without merging**
