### PR TITLE
Fix Windows build for PythonAPI

### PR DESCRIPTION
**Pull request by sgpearse**
CMakeLists.txt is currently missing the Python libraries on configuration.

15510c73eb4ddb04c4a2bd186374d16b65f28966: [clangTidyOutput.txt](https://output.circle-artifacts.com/output/job/a27d512d-db90-425a-9f6f-c97b3bd97e2d/artifacts/0/tmp/clangTidyOutput.txt)

### CODE REVIEW

**Review by StasJ — COMMENTED** [review]
Could this be fixed by just using the same version of Python in Windows as Linux/Mac in #3110?

**Comment by sgpearse** [comment]
> Could this be fixed by just using the same version of Python in Windows as Linux/Mac in https://github.com/NCAR/VAPOR/pull/3110?

Hypothetically, but Windows has so many quirks that it would take some digging.  [Here are our windows build notes](https://docs.google.com/document/d/1XNBmoUvxGn9I0fy9xvB1m5PQyOI32TtdyMbwfOve0QQ/edit) which have some strange caveats.  I don't know why the Unix platforms append "m" to their installation path and Windows does not.

I can try just removing the "m" from the third party library directory, which would leave CMakeLists.txt unchanged.  While our cmake file would be cleaner, there'd be an additional weird step for building Python on windows.  Alternatively, we could rebuild Python in #3110.  I think this would take a significant amount of time, particularly on windows.

Thoughts?

**Comment by StasJ** [comment]
The appended m signifies python was built with pyMalloc rather than the system malloc.

> Hypothetically, but Windows has so many quirks that it would take some digging. [Here are our windows build notes](https://docs.google.com/document/d/1XNBmoUvxGn9I0fy9xvB1m5PQyOI32TtdyMbwfOve0QQ/edit) which have some strange caveats. I don't know why the Unix platforms append "m" to their installation path and Windows does not.

I think it is the other way around, Unix uses non-m while windows uses m. It seems in your change it is explicitly requesting the non-m version on windows? Also you can specify multiple versions as valid options which the original code already does. It seems the only difference is the location of the python library within the third party libs which we should be able to have consistent between windows and non-windows?

**Comment by sgpearse** [comment]
@StasJ This is a rabbit hole that I'd like to revisit with #3110.  Windows builds take ~30 minutes to test for even slight changes.  

I think it's more effective to run tests when we update the rest of the 3rd party libraries, rather than minute changes like this.  If there's something imperative that we need, then I agree we should do it.  But I think this change is more effort than it's worth, unless I'm missing something.

**Comment by sgpearse** [comment]
@sgpearse will try adding the windows path to the NAMES and PATHS arguments which can take multiple values.

```        
find_library(
            Python_LIBRARIES
            NAMES python${PYTHONVERSION} python${PYTHONVERSION}m
            PATHS "${THIRD_PARTY_LIB_DIR}"
            NO_DEFAULT_PATH
        )```

**Comment by sgpearse** [comment]
@stasj I made the change to find_library() like we discussed, but it seems there are other compile issues that didn't arise for me when I first submitted this change last month.  I've taken a shot at fixing them but problems keep arising related to the "glad" library.  I've tried the following changes, which are not in this PR.  I can keep helping with this but I wanted to get your thoughts before continuing.

Add the following calls VAPOR/CMakeLists.txt around line 134:
```
include_directories("${PROJECT_SOURCE_DIR}/lib/osgl/include")
include_directories("${PROJECT_SOURCE_DIR}/lib/osgl/glad/include")
```

Additionally, make the following flags conditional in lib/osgl/glad/CMakeLists.txt at line 75:
```
if(NOT WIN32)
    target_compile_options(${LIB} PRIVATE -Wno-deprecated-declarations)
    target_compile_options(${LIB} PRIVATE -Wno-conversion-null)
endif ()
```

**Comment by clyne** [comment]
@sgpearse can we close this? Other options?

**Comment by sgpearse** [comment]
@clyne I don't think it should be closed until we're successfully building on windows.  The last time I was working on this, there were linker problems with the glad library.  As I understand, glad is a set of programmatically generated files that have needed some hand-manipulation.  It's something I'm pretty unfamiliar with.

**Comment by clyne** [comment]
How about labeling it as postponed or make it a draft so that we don't keep discussing? Note also that there is something weird because it says 179 files changed....

**Comment by sgpearse** [comment]
> How about labeling it as postponed or make it a draft so that we don't keep discussing?

Sounds good.

> Note also that there is something weird because it says 179 files changed....

That is weird.  This branch was derived from python_api and is being merged into main, but github doesn't seem to acknowledge that the python_api branch has been merged yet.  I don't know why, but the only file that's changed is the top level CMakeLists.txt.  I'm going to just close this one and open a new PR that branches off of main, and add a postponed label to that one.

**Pull request closed without merging**
