### PR TITLE
2d var support for flow

### PR DESCRIPTION
**Pull request by sgpearse**

### CODE REVIEW

**Comment by clyne** [comment]
@sgpearse, @shaomeng What does this PR do? It appears to configure the GUI for 2D variable support for the Flow renderer, but not address the backend renderer. If that's the case case it probably should not be submitted as a PR, but rather just made a remote branch can can be used to generate a fully functional 2D flow renderer. If it is fully functional it should reference the two open issues: #1950 and #1907. Make sense, or am I missing something?

**Comment by shaomeng** [comment]
@clyne I guess Scott wanted me to review the GUI first, so it's like a first step is completed. You can close this PR but don't delete this branch right now!

**Comment by shaomeng** [comment]
@sgpearse , I loaded this CF data and changed the dimensionality from 3D to 2D, it crashed. Could you take a look?

**Comment by shaomeng** [comment]
@sgpearse wants to ask @clyne: is it part of the requirement that 2D advection happens on irregular plains such as XZ and YZ, in addition to the normal XY plain?

**Comment by clyne** [comment]
> @clyne I guess Scott wanted me to review the GUI first, so it's like a first step is completed. You can close this PR but don't delete this branch right now!

Let's reserve PRs for branches that are ready to be merged into master, and just communicate shared branches via email. I will close the PR.

**Comment by clyne** [comment]
> @sgpearse wants to ask @clyne: is it part of the requirement that 2D advection happens on irregular plains such as XZ and YZ, in addition to the normal XY plain?

Eventually we may support 2D data with more general orientations, but for now it's safe to assume XY plane only.

**Comment by sgpearse** [comment]
@shaomeng Ok, that cm1.nc problem is now fixed.

**Comment by shaomeng** [comment]
Thanks Scott! Are you working on removing the 3rd row of variable selector
in 2D mode too?

**Comment by sgpearse** [comment]
3rd row removal should be in there now.

**Comment by shaomeng** [comment]
Did you push your change Scott? I still see it here:

[image: Screenshot from 2019-12-17 13-38-30.png]

**Pull request closed without merging**
