### PR TITLE
Windows installer

### LINKED ISSUE #3209: Windows CI build broken
The Windows build on CircleCI is not currently publishing an installer artifact.

### PR DESCRIPTION
**Pull request by sgpearse**
Partially fixes #3209 by addressing an issue Windows was having with the HDF5 initializer.

@stasj Could you take a look at the errors in osgl and vapi?  Here's [a link to the status](https://app.circleci.com/pipelines/github/NCAR/VAPOR/6059/workflows/29e42f7f-83c8-452c-a851-6e0386720391/jobs/14530/parallel-runs/0/steps/0-104) of our current build.

### CODE REVIEW

**Comment by StasJ** [comment]
> Partially fixes #3209 by addressing an issue Windows was having with the HDF5 initializer.
> 
> @StasJ Could you take a look at the errors in osgl and vapi? Here's [a link to the status](https://app.circleci.com/pipelines/github/NCAR/VAPOR/6059/workflows/29e42f7f-83c8-452c-a851-6e0386720391/jobs/14530/parallel-runs/0/steps/0-104) of our current build.

This PR is building on Windows for me so this may be an issue specific to Circle?

**Comment by sgpearse** [comment]
@stasj Could you grant me write permissions to your directory on cisl-vaporwin10.cis.ucar.edu?  Or alternatively copy the directory and give me write permissions on that one?  I'm hitting build errors on that machine, CircleCI, and two of my own windows computers.  I gotta find out what's different between those systems and the one you're building on.

**Comment by StasJ** [comment]
> @StasJ Could you grant me write permissions to your directory on cisl-vaporwin10.cis.ucar.edu? Or alternatively copy the directory and give me write permissions on that one? I'm hitting build errors on that machine, CircleCI, and two of my own windows computers. I gotta find out what's different between those systems and the one you're building on.

I was not using cisl-vaporwin10. It was a fresh windows/VS/third party lib install.

**Comment by sgpearse** [comment]
Ok, got it.  That's really strange.  I'm currently able to build, install, and run Vapor now though.  It required disabling the vapi build, as well as the the osgl tests for Windows.  I'm going test all of the platforms in a little bit, and if they all pass I'll re-request review.

**Review by StasJ — APPROVED** [review]

**Pull request merged**
