### PR TITLE
disable clip to box

### LINKED ISSUE #3216: Particle Renderer length scale gives incorrect results
1. Open the example DCP dataset
2. Create/enable a particle renderer and set the field variables
3. Enable `Show Direction`
4. Change `Length Scale`

Notice as you change the length scale, the number of particles as well as the direction of the existing particles change.

rec

### PR DESCRIPTION
**Pull request by sgpearse**
Fix #3216  which regards particles rendered with direction disappearing when they exceed domain bounds, by disabling clip-to-box.

### CODE REVIEW

**Review by StasJ — COMMENTED** [review]
Doesn’t this break the render region selector?

**Comment by sgpearse** [comment]
> Doesn’t this break the render region selector?

It does not, because only particles from within the box extents are queried from the Grid.  Particles outside the box won't be rendered at all, and with this change, particles within the extents will have clipping disabled.

However in testing this, it's raised a new issue that seems to be in the UnstructuredGrid3D class, #3243.

**Comment by sgpearse** [comment]
@stasj - I think we should be good to go here.  I can't currently re-request a review though, so I'm noting this via comment.

**Review by StasJ — APPROVED** [review]
Looks good to me!

**Pull request merged**
