### PR TITLE
Fix for #2058

### LINKED ISSUE #2058: Flow GUI Infinity Loop
To reproduce:
1. Open VAPOR, import CF compliant netcdf: `/glade/p/cisl/vast/vapor/Bugs/1950/rh_barry02l.2019071118.hwrfprs.storm.0p015.f003.nc`
2. Create a Flow renderer.
3. GUI enters infinity loop.

### PR DESCRIPTION
**Pull request by sgpearse**
Fix #2058

### CODE REVIEW

**Comment by sgpearse** [comment]
@StasJ I agree that it's a stop-gap.   Did you happen to see the comment in lines 318-320 though?

**Comment by StasJ** [comment]
@clyne yes, but that comment does not explain why this code is necessary and how it fixes the problem, or even that there is a problem to be fixed. For example, why does setting the first var to something prevent an infinite loop in the GUI?

**Comment by clyne** [comment]
> @clyne yes, but that comment does not explain why this code is necessary and how it fixes the problem, or even that there is a problem to be fixed. For example, why does setting the first var to something prevent an infinite loop in the GUI?

I assume this comment should have been directed to @sgpearse not clyne

**Comment by StasJ** [comment]
> > @clyne yes, but that comment does not explain why this code is necessary and how it fixes the problem, or even that there is a problem to be fixed. For example, why does setting the first var to something prevent an infinite loop in the GUI?
> 
> I assume this comment should have been directed to @sgpearse not clyne

Ah yes. I read this from an email thread that was initiated when you requested my review so it said "from clyne" in gmail

**Comment by clyne** [comment]
@sgpearse why was this PR closed? It hasn't been approved. It has unresolved comments that need to be approved by @StasJ

**Comment by sgpearse** [comment]
I've discarded my changes for this branch, and opened a new PR, #2065

**Pull request closed without merging**
