### PR TITLE
Slicer - Creates 2D grids of slice data

### PR DESCRIPTION
**Pull request by sgpearse**
This PR allows Renderers to construct a Slicer class that will deliver 2D grids based on RenderParams instances.  The spatial extents of a Grid class are insufficient to define a Slice's position and winding order, so Slicer also provides accessors to this information.

See SliceRenderer::_regenerateSlice() for an example of how renderers can sample data with it.  

SliceRenderer::_initVertexVBO() shows how to access an ordered list of six vertices that will correctly orient the two triangles of the texture.

SliceRenderer::_drawDebugPolygons() shows how to get debugging info from the Slicer.

ToDo: Run valgrind

### CODE REVIEW

**Review by clyne — COMMENTED** [review]
Scott, for the most part this looks good, but before getting into nitty gritty details I have two comments around
the design choice: 1. should "Slicer" be a class, and 2. is there a reason
it should be so tightly tied to the DataMgr and RenderParms classes? To me the functionality required looks more like a function than a class object. For one,
Slicer only does one thing: GetSlice(). Consider simply having a function
with a definition something like:

`RegularGrid *SliceGridAlongPlane(Grid *grid3d, Foo planeDescription, size_t w, size_t h, float *data)`

where grid3d is the 3d variable to be sampled, planeDescription describes
the plane (e.g. origin, normal vector), w and h give the width and
height of the sampled output plane, and data points to memory of
size w*h)

Not including DataMgr and RenderParams as arguments to this function
may mean that a few extra lines of code are required to use it, but
it makes the function far more general (it could be used, for
example, by the Python engine). It also does a better job of
information hiding; Slicer doesn't really need full access to the
DataMgr and RenderParams to do its job.
~

**Comment by sgpearse** [comment]
Thanks for the review.  I'll get on this after resolving #2906.  

The answers to your questions and comments are below.

> 1. should "Slicer" be a class?

The reason it's a class is because it holds the state for the following fields that need to be queried at different times during rendering:

1) The array of data allocated for the new RegularGrid
2) Winding-order of the vertices of the returned slice
3) Polygon edges for debugging

If the memory needs to be allocated by the renderer, that's fine.  My goal was to have an object create a Grid and maintain it, but it wasn't clear where we wanted memory management to happen.

Follow up: why do we want the renderer to manage the slice's memory?  This seems to mean  that all Renderers and PythonEngine interfaces will need to individually manage the allocated memory, rather than having it handled by the Slicer's destructor. 

> For one,
> Slicer only does one thing: GetSlice(). Consider simply having a function
> with a definition something like...

This follows the first rule of SOLID - Single responsibility principle.  I believe this is a good thing in general.  Am I missing something?

**Comment by clyne** [comment]
> Thanks for the review. I'll get on this after resolving #2906.
> 
> The answers to your questions and comments are below.
> 
> > 1. should "Slicer" be a class?
> 
> The reason it's a class is because it holds the state for the following fields that need to be queried at different times during rendering:
> 
> 1. The array of data allocated for the new RegularGrid
> 2. Winding-order of the vertices of the returned slice
> 3. Polygon edges for debugging

These variables are all calculated by GetSlice and could easily be returned by GetSlice(). Prefer local or parameters over member variables, and member variables over global variables. This improves readability of the code, and helps avoid side effects. E.g. if I call member function `foo` how do I know if it modifies/accesses member variable `bar`

> 
> If the memory needs to be allocated by the renderer, that's fine. My goal was to have an object create a Grid and maintain it, but it wasn't clear where we wanted memory management to happen.
> 
> Follow up: why do we want the renderer to manage the slice's memory? This seems to mean that all Renderers and PythonEngine interfaces will need to individually manage the allocated memory, rather than having it handled by the Slicer's destructor.

For one thing, if the user of Slicer deletes a Slicer instance then the Grid returned by GetSlicer becomes invalid. 

> 
> > For one,
> > Slicer only does one thing: GetSlice(). Consider simply having a function
> > with a definition something like...
> 
> This follows the first rule of SOLID - Single responsibility principle. I believe this is a good thing in general. Am I missing something?

**Comment by clyne** [comment]
> 

We have a DataMgrUtils module that provides functions that operate on the DataMgr. It might make sense to have "GridUtils" class for functions that operate on the Grid class.

**Pull request closed without merging**
