### PR TITLE
fix #104

### LINKED ISSUE #104: Capture Image only works for the 1st image
After successfully capture the 1st image, the image capturing functionality stops saving images on disk.

Note: this bug might be related to issue #50

### PR DESCRIPTION
**Pull request by shaomeng**
Please review my fix of bug #104 .

### CODE REVIEW

**Comment by clyne** [comment]
Sam, the call to paintEvent() in ControExec::Paint() appears inside of a SetSaveStateEnabled(false) and SetSaveStateEnabled(true) pair. You’re new changes prematurely return without completing the pair on error (when paintEvent() returns 0). This will break the session state mgt. SetSaveStateEnabled(true or false) and {Begin,End}StateSaveGroup() must always be called in pairs. 

Let me know if this isn’t clear.

jc

> On Oct 18, 2017, at 10:23 PM, Samuel Li <notifications@github.com> wrote:
> 
> @shaomeng requested your review on: NCAR/VAPOR#108 fix #104.
> 
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
SetSaveStateEnabled
John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu

**Comment by shaomeng** [comment]
John,

Thanks for the review.

I've added code surrounding paintEvent() to disable state saving when capturing the image, see commit https://github.com/NCAR/VAPOR/pull/108/commits/afaf7aa9a5b61947d1d5765684d801c6974f54c8. 

However, I couldn't find a single use of {Begin,End}StateSaveGroup() in the current code base. I suspect it's deprecated? 

Thanks,
Sam

**Comment by clyne** [comment]
> On Oct 19, 2017, at 10:27 AM, Samuel Li <notifications@github.com> wrote:
> 
> John,
> 
> Thanks for the review.
> 
> I've added code surrounding paintEvent() to disable state saving when capturing the image, see commit afaf7aa.

Terrific. I think I’ve successfully merged it via GitHub. For the first time ever I’m starting to think there are some benefits to using git :-)

> 
> However, I couldn't find a single use of {Begin,End}StateSaveGroup() in the current code base. I suspect it's deprecated?

Uh. I was using re syntax. It’s BeginSaveStateGroup and EndSaveStateGroup. Sorry

jc

> 
> Thanks,
> Sam
> 
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu

**Comment by shaomeng** [comment]
Yeah, I especially think it's helpful to have some of the git functionalities available from the web interface, instead of the commands from a terminal.

I did use fgrep to search for BeginSaveStateGroup and EndSaveStateGroup, and it's only in some comments. Could you verify that?

**Comment by clyne** [comment]
> On Oct 19, 2017, at 10:44 AM, Samuel Li <notifications@github.com> wrote:
> 
> Yeah, I especially think it's helpful to have some of the git functionalities available from the web interface, instead of the commands from a terminal.
> 
> I did use fgrep to search for BeginSaveStateGroup and EndSaveStateGroup, and it's only in some comments. Could you verify that?

It’s used pretty extensively. See below. The purpose of the begin/end groups is to capture a collection of state changes within the GUI as a single event. For example, if you are navigating with the mouse all of the viewing transforms between the mouse press and mouse release a captured as one event. This way when you do an undo the viewpoint will revert back to what it was before the mouse press (not one of the hundreds of viewpoint changes between a press and release). Make sense?

cheers- jc


cisl-arapahoe[356] grep BeginSaveStateGroup *cpp
ContourSubtabs.cpp:		_paramsMgr->BeginSaveStateGroup("Initialize ContourAppearanceSubtab");
ContourSubtabs.cpp:	// Do not BeginSaveStateGroup here!  This funciton
ContourSubtabs.cpp:		_paramsMgr->BeginSaveStateGroup("Transfer function change completed."
ContourSubtabs.cpp:		_paramsMgr->BeginSaveStateGroup("Set contour count.");
ContourSubtabs.cpp:		_paramsMgr->BeginSaveStateGroup("Set contour minimum.");
ContourSubtabs.cpp:		_paramsMgr->BeginSaveStateGroup("Set contour spacing.");
MappingFrame.cpp:  _paramsMgr->BeginSaveStateGroup("MappingFrame mousePressEvent");
Plot.cpp:	pMgr->BeginSaveStateGroup("Plot space range changing");
Plot.cpp:	pMgr->BeginSaveStateGroup("Set temporal extents for time plotting");
Plot.cpp:	pMgr->BeginSaveStateGroup("Initializing plot extent selectors"); 
Statistics.cpp:    pMgr->BeginSaveStateGroup("Add statistic in stats tool");
Statistics.cpp:	pMgr->BeginSaveStateGroup("Initializing statistics time spin boxes");
Statistics.cpp:	pMgr->BeginSaveStateGroup("Set Max timestep in Statistics app");
Statistics.cpp:	pMgr->BeginSaveStateGroup("Set Min timestep in Statistics app");
Statistics.cpp:    pMgr->BeginSaveStateGroup("Statistics range change");
TFWidget.cpp:	_paramsMgr->BeginSaveStateGroup("TFWidget::setCMVar(), "
TFWidget.cpp:	_paramsMgr->BeginSaveStateGroup("TFWidget::setSingleColor()");
VariablesWidget.cpp:	_paramsMgr->BeginSaveStateGroup(
VariablesWidget.cpp:	_paramsMgr->BeginSaveStateGroup(
ViewpointEventRouter.cpp:	paramsMgr->BeginSaveStateGroup("Light changed");
VizWin.cpp:	paramsMgr->BeginSaveStateGroup("Navigate scene");
VizWin.cpp:	paramsMgr->BeginSaveStateGroup("Navigate scene");
VizWinMgr.cpp:	paramsMgr->BeginSaveStateGroup("Navigate scene");

> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu

**Comment by shaomeng** [comment]
Aha, your 1st mention was  {Begin,End}StateSaveGroup(), instead of  {Begin,End}SaveStateGroup(). Note the word ordering. So I searched a wrong name. Sorry for the confusion.

The wrong term did exist in a few comments. Let me correct them along with my next merge request.

**Comment by clyne** [comment]
Oops. That’s my dyslexia :-) . Sorry.
jc

> On Oct 19, 2017, at 10:59 AM, Samuel Li <notifications@github.com> wrote:
> 
> Aha, your 1st mention was {Begin,End}StateSaveGroup(), instead of {Begin,End}SaveStateGroup(). Note the word ordering. So I searched a wrong name. Sorry for the confusion.
> 
> The wrong term did exist in a few comments. Let me correct them along with my next merge request.
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu

**Pull request merged**
