### PR TITLE
Issue 523

### PR DESCRIPTION
**Pull request by sgpearse**
Addition of Bounding Box Manipulators.

### CODE REVIEW

**Comment by sgpearse** [comment]
Hey John, regarding the code conventions, we've talked in the past about making implementation passes on a single branch, and cleanup passes in another branch.  This was to make it easier for the reviewer to suss out what's important in the code change.  Since you've seen the major changes, I think it's safer to do the cleanup.  I took to this as an implementation pass, not a refactorization.

**Comment by clyne** [comment]
Scott, sorry I don’t recall that discussion. In any event it speeds the review process if the conventions are followed. 

thanks - jc

> On Jun 7, 2018, at 3:44 PM, sgpearse <notifications@github.com> wrote:
> 
> Hey John, regarding the code conventions, we've talked in the past about making implementation passes on a single branch, and cleanup passes in another branch. This was to make it easier for the reviewer to suss out what's important in the code change. Since you've seen the major changes, I think it's safer to do the cleanup. I took to this as an implementation pass, not a refactorization.
> 
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

John Clyne
National Center for Atmospheric Research
303.497.1236 (w), 303.809.1922 (c)
clyne@ucar.edu

**Comment by sgpearse** [comment]
Hey John, feel free to check out the changes.  I believe I've addressed everything.  The Update() method needs all those parameters for reasons we've talked about.  There are strategies we can use to reduce this, particularly by setting up the ModelView and Projection matrices during mouse events.  Currently, they only get set up during render events.

**Comment by sgpearse** [comment]
All noted items are fixed in the current pull request.

**Pull request merged**
