### PR TITLE
Fix win

### LINKED ISSUE #3178: Windows build currently broken
PR #3152 takes some steps towards building on windows with BUILD_PYTHON=ON, but when it's off our build still fails due to ~osgl~ glad linker problems.

### PR DESCRIPTION
**Pull request by StasJ**
Fix #3178

### CODE REVIEW

**Comment by clyne** [comment]
@sgpearse will resolve merge conflicts and review

**Comment by sgpearse** [comment]
@stasj - Thanks for helping on this.  I fixed the merge conflict. There are a few warnings - could you mend those and then we can merge?

**Comment by clyne** [comment]
@sgpearse this is passing now. Do you approve?

**Comment by sgpearse** [comment]
@clyne yep - I just needed to confirm that the build was succeeding.

**Review by sgpearse — APPROVED** [review]

**Pull request merged**
