### PR TITLE
Constrain when V*SliderEdit emits its signals

### LINKED ISSUE #2390: Changing the slider minimum value will result in the minimum changed signal being emitted 10 times
This will cause 10 undo steps and 10 renders which can potentially be very costly.

To reproduce, change the minimum value for the Volume ambient lighting slider in the renderer_gui_refactor branch.

### PR DESCRIPTION
**Pull request by sgpearse**
Fixes #2390, which reported that the V*SliderEdit emits unnecessary signals.

### CODE REVIEW

**Review by StasJ — CHANGES_REQUESTED** [review]
1. Pick any double slider
1. Set the value to the max
1. Right click and change the max to half the current max

The changed signal is emitted twice.

**Comment by sgpearse** [comment]
This is a good catch.  I believe the correct fix lies with the P*SliderEdit.  

The current PR changes the P*SliderEdit::valueChanged() function to account for all situations where multiple V*SliderEdit signals are emitted; within a a ParamsGroup.

**Review by StasJ — CHANGES_REQUESTED** [review]
Your changes to the PSliderEdit break its functionality. It is only supposed to change the custom range in the params if the use manually sets them. Otherwise it will never be able to update programmatically if needed.

**Comment by sgpearse** [comment]
These new changes constrain the minimum and maximum range values to always include the currently selected value.  IE if the current value is 0, the user cannot change the min to 1, or max to -1.

These changes also resolve the slider bug reported in #2407

**Review by StasJ — APPROVED** [review]

**Comment by StasJ** [comment]
#2407 is not fixed by the way. It changes the text in the textbox but the emitted value is still wrong.

**Comment by sgpearse** [comment]
Hmm.  I cannot reproduce what you're seeing.

I've added a print statement in PDoubleSlierEdit for the emitted signal value and for me it aligns with what the text displays.  Are you seeing different values, or are you testing in a different way?

**Comment by StasJ** [comment]
> Hmm. I cannot reproduce what you're seeing.
> 
> I've added a print statement in PDoubleSlierEdit for the emitted signal value and for me it aligns with what the text displays. Are you seeing different values, or are you testing in a different way?

When it emits the signal it is the max but it doesn't always emit the signal.

**Comment by sgpearse** [comment]
I've reverted the print statement. 

The tests I'm running give correct results, but at this point #2407 should be discussed as a separate issue.

**Comment by StasJ** [comment]
> I've reverted the print statement.
> 
> The tests I'm running give correct results, but at this point #2407 should be discussed as a separate issue.

I'm fine with postponing this issue. I've already approved the PR.

Note the inconsistent brightness below:

slider2

**Comment by clyne** [comment]
@sgpearse this PR has been approved but isn't passing CircleCI checks. Please fix.

**Pull request merged**
