### PR TITLE
Fix #3574 - Slice renderer not rendering until after timestep changed

### LINKED ISSUE #3574: Slice renderer not rendering until after timestep changed
1. On casper, open ROMS/his
2. Create/enable a slice renderer

Notice nothing is drawn

3. Step forward a timestep
4. Step back to the original timestep

Notice data has appeared

### PR DESCRIPTION
**Pull request by sgpearse**
The ROMS/his dataset was setting a default variable that was all 0's, causing a problem for the Slice shader's color lookup table.  This PR artificially adds .1 to the maximum data value maximum so that there is some kind of an actual range in the case where the data's minimum==maximum.

Fixes #3574

### CODE REVIEW

**Review by StasJ — CHANGES_REQUESTED** [review]
This should be fixed in the slice and contour renderers rather than having DataMgr::GetDataRange return an incorrect value.

**Review by StasJ — COMMENTED** [review]
This will present the user with incorrect information since it is writing the hacked value back into the params database. This may also still break for values >2.1M, although this is an unlikely scenario.

**Comment by sgpearse** [comment]
Ok I see what you mean.  In the current state of this PR, the range modification does not affect the params database, and I'm using FLT_EPSILON instead of .1.

**Review by StasJ — COMMENTED** [review]
Thanks for addressing this, Scott.
Some notes:
- Using FLT_EPSILON will make this not work for values > 1
- I noticed that the contour renderer does not have this issue in main.
- The 2D renderer does have this issue.

**Comment by sgpearse** [comment]
Will choose an arbitrary value instead of adding a delta.

**Review by StasJ — APPROVED** [review]
Looks great, thanks Scott.

**Pull request merged**
