### PR TITLE
#2419 Streamline data file name is hard to modify

### LINKED ISSUE #2419: Flow: Streamline data file name is hard to modify
The output file for writing streamline data may only be set to existing file names.  Users will want to customize a new output file name.

Case 1:
1. Open Vapor with any dataset and create a Flow Renderer
2. In the Seeding tab, try to modify the default file under the "Write Flowlines to File" section

Case 2:
1. Open Vapor with any dataset and create a Flow Renderer
2. In the Seeding tab, click the "Select" button in the "Write Flowlines to File section
3. The dialog will not accept a new file name, only allowing the selection of preexisting files

### PR DESCRIPTION
**Pull request by StasJ**
Fix #2419

### CODE REVIEW

**Comment by shaomeng** [comment]
@StasJ  maybe the widget you really wanted to change is the widget labelled "Target file" ?

**Comment by StasJ** [comment]
> @StasJ maybe the widget you really wanted to change is the widget labelled "Target file" ?

Fixed

**Comment by shaomeng** [comment]
I still cannot figure out a way to change the file name with this new widget, at least on Ubuntu system. Maybe @sgpearse can verify its behavior on MacOS ?

**Comment by sgpearse** [comment]
I'm unfortunately not able to modify the file name through the control panel's VLineEdit, or the file-dialog.

There may be a reason that we're not using the VFileSelector class for this.  This class has been tested and in place since 3.2.

**Comment by clyne** [comment]
@sgpearse, @shaomeng please confirm whether you can or can't enter a file name.

**Review by shaomeng — APPROVED** [review]
The pop-up window is indeed able to change the filename, thus I'm approving this PR.

**Review by sgpearse — APPROVED** [review]

**Comment by clyne** [comment]
@StasJ this PR has a conflict. As soon as you resolve we can merge.

**Comment by StasJ** [comment]
> @StasJ this PR has a conflict. As soon as you resolve we can merge.

@clyne Done.

**Comment by clyne** [comment]
@sgpearse this PR failed to build on the Mac. It looks like you've been messing with Circle. So is this Stas' problem or yours?

cc @StasJ

**Comment by StasJ** [comment]
> @sgpearse this PR failed to build on the Mac. It looks like you've been messing with Circle. So is this Stas' problem or yours?
> 
> cc @StasJ

@clyne master was failing and I merged master into this branch to resolve the conflict. The issue is on master, not this branch.

**Pull request merged**
