### PR TITLE
Fix #2537 by documenting the usage of the flow list-of-seeds file

### LINKED ISSUE #2537: Flow: file format for "list of seeds" not documented
There is no context help in the GUI describing the format for the file used when Seed Distribution Type is set to "list of seeds".

### PR DESCRIPTION
**Pull request by sgpearse**
Explained the usage of the list-of-seeds file by adding a demo file and tooltip.

Fixed #2537

### CODE REVIEW

**Review by clyne — COMMENTED** [review]
@shaomeng how is the time step value treated in the seed list file when generating *stream* lines? Is it simply ignored? The user may want to specify a spatial seed locations that apply to *all* time steps, particularly when generating stream lines. One option, if it doesn't already exist, is to have a special value (e.g. -1) indicate that seeds should be injected at all time steps, and this would apply to both stream lines and path lines.

**Comment by shaomeng** [comment]
Let me investigate #2543 first so this tool tip can be as accurate as possible.

**Comment by shaomeng** [comment]
> @shaomeng how is the time step value treated in the seed list file when generating _stream_ lines? Is it simply ignored? The user may want to specify a spatial seed locations that apply to _all_ time steps, particularly when generating stream lines. One option, if it doesn't already exist, is to have a special value (e.g. -1) indicate that seeds should be injected at all time steps, and this would apply to both stream lines and path lines.

Given the complexity of the current GUI and available controls, I don't think it's a good idea to invent a seed list syntax that is capable to express those GUI controls. I propose the following:

1) Seed list is used to only specify location information, but not temporal information.
2) In both steady and unsteady flow cases, the temporal information of imported seeds is fixed to whatever the current time step is. 
3) Use cases such as repeated seed injection is only controlled via GUI.

Note: this proposed behavior is consistent with how seed time is determined in other seed generation methods.

**Comment by sgpearse** [comment]
See issue #2543 for desired behavior

**Review by clyne — APPROVED** [review]

**Review by shaomeng — APPROVED** [review]

**Pull request merged**
