### PR TITLE
Signal to docs repository on release

### PR DESCRIPTION
**Pull request by ifranda**
Workflow that triggers our documentation workflow in our other repo on release. This will automate one more step of the release process.

### CODE REVIEW

**Comment by sgpearse** [comment]
@ifranda Hey Ian, I thought the VaporDocumentationWebsite watched this repository for new releases in order to trigger the docs rebuild.  Is that not true?  If true, why is this needed?

**Comment by ifranda** [comment]
Unfortunately I think the way actions are set up means that an action can only watch for a trigger in its own repository, so if we want to run the documentation workflow automatically we'll need a workflow here to pass along the signal. 

But automating this doesn't save that much time -- we can always run the documentation workflow manually just by clicking a button and it takes just ~5 minutes to run. And if we want to manually review the PR it creates it'll take some manual work anyway. What are your thoughts on this?

**Comment by sgpearse** [comment]
> Unfortunately I think the way actions are set up means that an action can only watch for a trigger in its own repository, so if we want to run the documentation workflow automatically we'll need a workflow here to pass along the signal.

Interesting.  I thought the docs were auto-generated in [this commit](https://github.com/NCAR/VaporDocumentationWebsite/commit/16de6b95b9f47cd3ca1a3b204687d5e5d4adc6bd) by the GHA[bot] since you were on PTO.  So I guess this was manually generated by yourself?

> But automating this doesn't save that much time -- we can always run the documentation workflow manually just by clicking a button and it takes just ~5 minutes to run. And if we want to manually review the PR it creates it'll take some manual work anyway. What are your thoughts on this?

I'd say always automate stuff like this.  If the work is a one-off job then sometimes doing it manually is easier, but we will be needing to do this repeatedly on each release.  We'll still need to add an action item to verify the website, so I'll do that now.

Another helpful contribution Ian.  Thank you :)

**Comment by ifranda** [comment]
> Interesting. I thought the docs were auto-generated in [this commit](https://github.com/NCAR/VaporDocumentationWebsite/commit/16de6b95b9f47cd3ca1a3b204687d5e5d4adc6bd) by the GHA[bot]

I manually went in to trigger the workflow and merge the PR for this but it only takes a few minutes. 

On a side note, we can also manually trigger the documentation workflow to generate the docs when we make a documentation update! There might be cases where this is beneficial since it's generated on a remote linux machine and always uses the latest conda releases for the sphinx packages.

**Pull request merged**
