### PR TITLE
Sphinx gallery implementation of netCDF examples

### PR DESCRIPTION
**Pull request by sgpearse**
This PR does some restructuring on our "unsupported NetCDF" section, and uses the sphinx-gallery module instead of jupyter-sphinx.

The advantage that sphinx-gallery has over jupyter-sphinx is that it automatically generates web pages from the python scripts we use to demonstrate CF Compliance.  Additionally, it generates .ipynb files, and automatically provides links to download them, and the python files that were their basis.

Navigate to the "unsupported NetCDF" section through the following links in the table of contents:

- Getting Data into Vapor
    - Importing unsupported data
        - NetCDF

The current state of readTheDocs_bigUpdate [can be viewed here](https://vapor.readthedocs.io/en/latest/data/netCDF/cfComplianceTOC.html).

The changes introduced by this PR [can be viewed here](https://vapor.readthedocs.io/en/sphinx-gallery/data/netCDF/cfCompliance.html).

### CODE REVIEW

**Review by clyne — COMMENTED** [review]
**Menu**:
Under "importing unsupported data" the second menu item is "Non CF compliant NetCDF". This is not really descriptive of the content covered in the section, because the "unsupported" data aren't necessarily NetCDF files that are not CF compliant. The could be, for example, HDF5 files. The examples provided in the section this menu item links to could easily be modified to read in HDF5 data. How about renaming this to something simple like "Other data formats"?

[unsupported data](https://vapor.readthedocs.io/en/latest/data/importingUnsupportedData.html)

1. The grid terminology is really important to get right. If users don't understand what we mean by stretched or regular grids it is hard to interpret the table. Unfortunately, the terminology used by the [wiki](https://en.wikipedia.org/wiki/Regular_grid) is not consistent with our own. In particular, we say "stretched grid", the wiki link says "rectilinear". I think you need to explicitly state that the wiki link above describes the structured grids that we support (regular, rectilinear, curvilinear), with the caveat that we use the term "stretched" instead of "rectilinear".
2. Move the VDC paragraph to the end, after the discussion of curvilinear grids, because VDC is the option of last resort. 

[BOV section
](https://vapor.readthedocs.io/en/latest/data/brickOfValues.html)

1. The text says that BOV supports "rectilinear" data. According to the wiki reference you've used [here](https://en.wikipedia.org/wiki/Regular_grid), "rectilinear" is what we call a stretched grid. Shouldn't this be "regular"? I'd add a link to the wiki page to make this clear.

[stretchedGridExample](https://vapor.readthedocs.io/en/latest/data/netCDF/stretchedGridExample.html)

1. This example is identical to the regularGridExample. Shouldn't you be explicit in stating that you are using numpy.geomspace to generate logarithmic coordinates, and the fact that from a data preparation standpoint there is no real difference between stretched (rectilinear) and regular grids?

**Comment by sgpearse** [comment]
@clyne - Sorry, there's a little bit of confusion here.  My description for this PR has two links - one to the old documentation, one to what is new in this PR.  You're referencing the old one.  Here's [another link to the new one](https://vapor.readthedocs.io/en/sphinx-gallery/index.html).

But your points still stand and I've made some changes described below.  I also have a couple questions.

> Menu:
> Under "importing unsupported data" the second menu item is "Non CF compliant NetCDF". This is not really descriptive of the content covered in the section, because the "unsupported" data aren't necessarily NetCDF files that are not CF compliant. The could be, for example, HDF5 files. The examples provided in the section this menu item links to could easily be modified to read in HDF5 data. How about renaming this to something simple like "Other data formats"?

I agree. Fixed.

> unsupported data
> The grid terminology is really important to get right. If users don't understand what we mean by stretched or regular grids it is hard to interpret the table. Unfortunately, the terminology used by the wiki is not consistent with our own. In particular, we say "stretched grid", the wiki link says "rectilinear". I think you need to explicitly state that the wiki link above describes the structured grids that we support (regular, rectilinear, curvilinear), with the caveat that we use the term "stretched" instead of "rectilinear".

I've gone ahead and removed the term "stretched" from the docs in lieu of "rectilinear".  I'm wondering if we should abandon the use of the "stretched" term even outside our documentation.

> Move the VDC paragraph to the end, after the discussion of curvilinear grids, because VDC is the option of last resort.

This was previously changed on the new branch, but not the old one.  [Link here](https://vapor.readthedocs.io/en/sphinx-gallery/data/otherDataFormats.html).

> BOV section
> The text says that BOV supports "rectilinear" data. According to the wiki reference you've used here, "rectilinear" is what we call a stretched grid. Shouldn't this be "regular"? I'd add a link to the wiki page to make this clear.

Fixed, with wiki link added in a note.  [Link](https://vapor.readthedocs.io/en/sphinx-gallery/data/brickOfValues.html).

> stretchedGridExample
> This example is identical to the regularGridExample. Shouldn't you be explicit in stating that you are using numpy.geomspace to generate logarithmic coordinates...

I've added further comments in the examples where geomspace and linspace are used.  Was there another place to state this that you had in mind?  Links: [top level CF examples page](https://vapor.readthedocs.io/en/sphinx-gallery/data/netCDF/examples/index.html), [cartesian example](https://vapor.readthedocs.io/en/sphinx-gallery/data/netCDF/examples/cartesianGridExample.html#sphx-glr-data-netcdf-examples-cartesiangridexample-py), and [rectilinear example](https://vapor.readthedocs.io/en/sphinx-gallery/data/netCDF/examples/rectilinearGridExample.html#sphx-glr-data-netcdf-examples-rectilineargridexample-py).

>...and the fact that from a data preparation standpoint there is no real difference between stretched (rectilinear) and regular grids?

I'm not sure where to state this.  We could state it on the [top level CF examples page](https://vapor.readthedocs.io/en/sphinx-gallery/data/netCDF/examples/index.html), but over time our examples will grow and I don't think this subtlety is relevant information for users.  I believe most people will click on the example that is relevant to them, and ignore the others.  Either way, I can add it on the above linked page, or somewhere else that you think is suitable.

**Comment by clyne** [comment]
> @clyne - Sorry, there's a little bit of confusion here. My description for this PR has two links - one to the old documentation, one to what is new in this PR. You're referencing the old one. Here's [another link to the new one](https://vapor.readthedocs.io/en/sphinx-gallery/index.html).
> 
> But your points still stand and I've made some changes described below. I also have a couple questions.
> 
> > Menu:
> > Under "importing unsupported data" the second menu item is "Non CF compliant NetCDF". This is not really descriptive of the content covered in the section, because the "unsupported" data aren't necessarily NetCDF files that are not CF compliant. The could be, for example, HDF5 files. The examples provided in the section this menu item links to could easily be modified to read in HDF5 data. How about renaming this to something simple like "Other data formats"?
> 
> I agree. Fixed.
> 
> > unsupported data
> > The grid terminology is really important to get right. If users don't understand what we mean by stretched or regular grids it is hard to interpret the table. Unfortunately, the terminology used by the wiki is not consistent with our own. In particular, we say "stretched grid", the wiki link says "rectilinear". I think you need to explicitly state that the wiki link above describes the structured grids that we support (regular, rectilinear, curvilinear), with the caveat that we use the term "stretched" instead of "rectilinear".
> 
> I've gone ahead and removed the term "stretched" from the docs in lieu of "rectilinear". I'm wondering if we should abandon the use of the "stretched" term even outside our documentation.

Good. But in this version the term "Cartesian grid" is used where it should be "Regular grid". A Cartesian grid is a special case of a Regular grid where all of the cells are squares (2D), or cubes (3D). See the wiki reference you've linked. You'll need to find all occurrences of Cartesian and replace with Regular. 

Re stretched vs rectilinear: Stretched is the term many modelers use, and it is also used it is all over our documentation. I think we just need to be clear that stretched is equivalent to rectilinear. 

> 
> > Move the VDC paragraph to the end, after the discussion of curvilinear grids, because VDC is the option of last resort.
> 
> This was previously changed on the new branch, but not the old one. [Link here](https://vapor.readthedocs.io/en/sphinx-gallery/data/otherDataFormats.html).

Now the section on curvilinear and rectilinear grids is gone completely. Between the paragraph on the BOV format and the one on the VDC format I'd like to see something like:

_If your data are sampled on rectilinear or curvilinear grids, or if they regular, but stored in a format other than raw binaries, converting your data to CF compliant NetCDF is probably your best bet. CF NetCDF is widely used in the earth sciences, is highly flexible, and there is a large ecosystem of software tools that are capable reading, writing, and manipulating CF NetCDF files._

> 
> > BOV section
> > The text says that BOV supports "rectilinear" data. According to the wiki reference you've used here, "rectilinear" is what we call a stretched grid. Shouldn't this be "regular"? I'd add a link to the wiki page to make this clear.
> 
> Fixed, with wiki link added in a note. [Link](https://vapor.readthedocs.io/en/sphinx-gallery/data/brickOfValues.html).
> 
> > stretchedGridExample
> > This example is identical to the regularGridExample. Shouldn't you be explicit in stating that you are using numpy.geomspace to generate logarithmic coordinates...
> 
> I've added further comments in the examples where geomspace and linspace are used. Was there another place to state this that you had in mind? Links: [top level CF examples page](https://vapor.readthedocs.io/en/sphinx-gallery/data/netCDF/examples/index.html), [cartesian example](https://vapor.readthedocs.io/en/sphinx-gallery/data/netCDF/examples/cartesianGridExample.html#sphx-glr-data-netcdf-examples-cartesiangridexample-py), and [rectilinear example](https://vapor.readthedocs.io/en/sphinx-gallery/data/netCDF/examples/rectilinearGridExample.html#sphx-glr-data-netcdf-examples-rectilineargridexample-py).
> 

Looks good.

> > ...and the fact that from a data preparation standpoint there is no real difference between stretched (rectilinear) and regular grids?
> 
> I'm not sure where to state this. We could state it on the [top level CF examples page](https://vapor.readthedocs.io/en/sphinx-gallery/data/netCDF/examples/index.html), but over time our examples will grow and I don't think this subtlety is relevant information for users. I believe most people will click on the example that is relevant to them, and ignore the others. Either way, I can add it on the above linked page, or somewhere else that you think is suitable.

Sounds good.

**Comment by sgpearse** [comment]
> Good. But in this version the term "Cartesian grid" is used where it should be "Regular grid". A Cartesian grid is a special case of a Regular grid where all of the cells are squares (2D), or cubes (3D). See the wiki reference you've linked. You'll need to find all occurrences of Cartesian and replace with Regular.

You're correct.  Fixed on [this page](https://vapor.readthedocs.io/en/sphinx-gallery/data/otherDataFormats.html#).  There are subsequent examples that do use cartesian grids, so the terminology for those hasn't been changed.

> Re stretched vs rectilinear: Stretched is the term many modelers use, and it is also used it is all over our documentation. I think we just need to be clear that stretched is equivalent to rectilinear.

A note on this has been added.  [Link here](https://vapor.readthedocs.io/en/sphinx-gallery/data/otherDataFormats.html#).

> Now the section on curvilinear and rectilinear grids is gone completely. Between the paragraph on the BOV format and the one on the VDC format I'd like to see something like...

This paragraph has been added along with some in-line links to the relevant NetCDF and VDC documentation.  [Link here](https://vapor.readthedocs.io/en/sphinx-gallery/data/otherDataFormats.html#).

> > I'm not sure where to state this. We could state it on the top level CF examples page, but over time our examples will grow and I don't think this subtlety is relevant information for users. I believe most people will click on the example that is relevant to them, and ignore the others. Either way, I can add it on the above linked page, or somewhere else that you think is suitable.
> 
> Sounds good.

Note added in the [top-level CF examples page](https://vapor.readthedocs.io/en/sphinx-gallery/data/netCDF/examples/index.html).

**Review by clyne — APPROVED** [review]

**Pull request merged**
