### PR TITLE
Issue 2161

### PR DESCRIPTION
**Pull request by sgpearse**
This PR changes the format of our renderer documentation. Each renderer is now discussed individually in three categories: Description, Basic Controls, and Specialized Controls. Each renderer now has a video tutorial located at the top of their documentation.

This PR includes the documentation for the Flow renderer, referenced in #2161.

If you want to see the changes in this PR, check out the branch issue_2161 and open the file below in a web browser:

<vapor-repository>/docs/index.html

### CODE REVIEW

**Comment by shaomeng** [comment]
@sgpearse I've made a few minor changes in this commit: 0eebe483 .
I hope they make sense. 
Other parts of the PR looks good!

**Comment by sgpearse** [comment]
@shaomeng FYI, we need to run sphinx on the .rst files to update our .html, which is what's hosted by github.  I've done this in an upcoming push.

@clyne 

> @shaomeng the description for Pathline length states "This specifies how many previous locations of a pathline...". The term "locations" is pretty ambiguous, and I'm not sure what it means. Is it the number of time steps, or something else? If it is time steps we should still define what this means: the number of time steps is the number of temporal samples (aka "snapshots" in a data set).

Everything has been written to my best understanding of the algorithms.  I'll have to convene with Sam with the correct wording tomorrow.

**Comment by shaomeng** [comment]
> The videos are really great!
> 
> @shaomeng the description for Pathline length states "This specifies how many previous locations of a pathline...". The term "locations" is pretty ambiguous, and I'm not sure what it means. Is it the number of time steps, or something else? If it is time steps we should still define what this means: the number of time steps is the number of temporal samples (aka "snapshots" in a data set).
> --> I can further improve these descriptions, but how should we proceed these html changes at a large scale and at at a long run? Should I write Scott an email with the new paragraph, or should I locate the source file that's responsible of the html?
> 
> The example "list of seeds" doesn't make sense to me. If the only delimiter is a comma how do you distinguish between the X,Y,Z and X,Y,Z,T case (the documentation says T is optional). How is the T interpreted for streamlines? How is Z interpreted for 2D flow, is it simply ignored?
> --> The "list of seeds" importer currently reads 3 or 4 values from a line. More values from the same line will be ignored. If there are less than 3 values, an error will be thrown. So, no 2D seed capability yet. Need more thinking on how it operates actually.
> --> Regarding pathine vs streamline, the list of seeds doesn't control how that operates. The streamline logic is to advect particles to a certain timestamp. If the input seeds have time values smaller than that timestamp, they'll get advected to that timestamp. If they have time values greater than that timestamp, they simply won't be advected, thus not shown on the screen.
> 
> @sgpearse is @StasJ offscreen rendering capability documented?



> The videos are really great!
> 
> @shaomeng the description for Pathline length states "This specifies how many previous locations of a pathline...". The term "locations" is pretty ambiguous, and I'm not sure what it means. Is it the number of time steps, or something else? If it is time steps we should still define what this means: the number of time steps is the number of temporal samples (aka "snapshots" in a data set).
--> I can further improve these descriptions, but how should we proceed these html changes at a large scale and at at a long run? Should I write Scott an email with the new paragraph, or should I locate the source file that's responsible of the html?
> 
> The example "list of seeds" doesn't make sense to me. If the only delimiter is a comma how do you distinguish between the X,Y,Z and X,Y,Z,T case (the documentation says T is optional). How is the T interpreted for streamlines? How is Z interpreted for 2D flow, is it simply ignored?
--> The "list of seeds" importer currently reads 3 or 4 values from a line. More values from the same line will be ignored. If there are less than 3 values, an error will be thrown. So, no 2D seed capability yet. Need more thinking on how it operates actually.
--> Regarding pathine vs streamline, the list of seeds doesn't control how that operates. The streamline logic is to advect particles to a certain timestamp. If the input seeds have time values smaller than that timestamp, they'll get advected to that timestamp. If they have time values greater than that timestamp, they simply won't be advected, thus not shown on the screen.
> 
> @sgpearse is @StasJ offscreen rendering capability documented?

**Comment by clyne** [comment]
> > The videos are really great!
> > @shaomeng the description for Pathline length states "This specifies how many previous locations of a pathline...". The term "locations" is pretty ambiguous, and I'm not sure what it means. Is it the number of time steps, or something else? If it is time steps we should still define what this means: the number of time steps is the number of temporal samples (aka "snapshots" in a data set).
> 
> --> I can further improve these descriptions, but how should we proceed these html changes at a large scale and at at a long run? Should I write Scott an email with the new paragraph, or should I locate the source file that's responsible of the html?
> 
> > The example "list of seeds" doesn't make sense to me. If the only delimiter is a comma how do you distinguish between the X,Y,Z and X,Y,Z,T case (the documentation says T is optional). How is the T interpreted for streamlines? How is Z interpreted for 2D flow, is it simply ignored?
> 
> --> The "list of seeds" importer currently reads 3 or 4 values from a line. More values from the same line will be ignored. If there are less than 3 values, an error will be thrown. So, no 2D seed capability yet. Need more thinking on how it operates actually.
> --> Regarding pathine vs streamline, the list of seeds doesn't control how that operates. The streamline logic is to advect particles to a certain timestamp. If the input seeds have time values smaller than that timestamp, they'll get advected to that timestamp. If they have time values greater than that timestamp, they simply won't be advected, thus not shown on the screen.
> 
> > @sgpearse is @StasJ offscreen rendering capability documented?

@shaomeng @sgpearse the example for the "list of seeds" documentation shows 8 values written on a single line. From your description above it sounds like a newline is the delimiter between each point. I.e. There should be four values per line,  not 8. Correct?

Regarding 2D seed lists: Sam, how about we open a GitHub issue for this?

Regarding streamlines and time: I think streamline advection should simply ignore the timestamp. Among other reasons, many data sets don't have a user generated time stamp and VAPOR simply makes one up. These made up timestamps are not apparent to the user and it will make specifying a seed list unnecessarily difficult. Plus, the notion of time is really meaningless for streamlines.

**Comment by shaomeng** [comment]
> @shaomeng @sgpearse the example for the "list of seeds" documentation shows 8 values written on a single line. From your description above it sounds like a newline is the delimiter between each point. I.e. There should be four values per line, not 8. Correct?

The current code ignores whatever in the same line after collecting 4 values. I think for documentation and example purposes, Scott should use a line of 4 values, instead of 8.

**Comment by sgpearse** [comment]
All comments have been addressed, and changes are now pushed to origin.

**Pull request merged**
