### PR TITLE
Fix Graphics Card available memory detection issue #3312

### LINKED ISSUE #3312: Graphics Card available memory detection issue
The current graphics card available memory detection and logic seem to be too restrictive. For example, I cannot even render a 64^3 dataset on my AMD system with an integrated graphics card because of a lack of available memory. This requirement might need to be relaxed or even removed, maybe for selected vendors (e.g., AMD) only.

### PR DESCRIPTION
**Pull request by StasJ**
Fix #3312

### CODE REVIEW

**Comment by shaomeng** [comment]
CMake fails to configure VAPOR, thus I cannot build VAPOR, on my personal desktop that's equipped with AMD graphics. As a result, I cannot test this fix. 

I can still test if there's an installer incorporated this fix though.

**Review by shaomeng — APPROVED** [review]
CMake fails to configure VAPOR, thus I cannot build VAPOR, on my personal desktop that's equipped with AMD graphics. As a result, I cannot test this fix.

I can still test if there's an installer incorporated this fix though. But this fix seems easy enough that I'm confident that it has the work done, so I'm fine merging without testing too.

**Comment by sgpearse** [comment]
@shaomeng - Can you submit a ticket if CMake is failing?  I cannot reproduce it on this or any other branch I've worked with recently.

**Comment by shaomeng** [comment]
> @shaomeng - Can you submit a ticket if CMake is failing? I cannot reproduce it on this or any other branch I've worked with recently.

Not sure how a ticket can help if it's a problem on my computer alone, in which case I consider it low priority. The error is like below:
```
sam@Navada:~/Git/VAPOR/build$ cmake ..
Library NETCDF   = /usr/local/VAPOR-Deps/2019-Aug/lib/libnetcdf.so
Library UDUNITS2 = /usr/local/VAPOR-Deps/2019-Aug/lib/libudunits2.so
Library FREETYPE = /usr/local/VAPOR-Deps/2019-Aug/lib/libfreetype.so
Library GEOTIFF  = /usr/local/VAPOR-Deps/2019-Aug/lib/libgeotiff.so
Library JPEG     = /usr/local/VAPOR-Deps/2019-Aug/lib/libjpeg.so
Library HDF5_LIB = /usr/local/VAPOR-Deps/2019-Aug/lib/libhdf5.so
Library EXPAT = EXPAT-NOTFOUND
Using bundled python
Python Found 
	Python_VERSION = '3.6'
	Python_NumPy_VERSION = 'UNUSED IN BUNDLED PYTHON'
	Python_LIBRARIES = 'Python_LIBRARIES-NOTFOUND' **NOT FOUND**
	Python_INCLUDE_DIRS = '/usr/local/VAPOR-Deps/2019-Aug/include/python3.6m' **NOT FOUND**
	Python_SITELIB = '/usr/local/VAPOR-Deps/2019-Aug/lib/python3.6/site-packages' **NOT FOUND**
	Python_NumPy_INCLUDE_DIRS = '/usr/local/VAPOR-Deps/2019-Aug/lib/python3.6/site-packages/numpy/core/include' **NOT FOUND**
CMake Error at apps/vaporgui/CMakeLists.txt:345 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
See also "/home/sam/Git/VAPOR/build/CMakeFiles/CMakeOutput.log".
```

**Comment by sgpearse** [comment]
Hmm.  What version of Ubuntu is this?  I'm guessing 22?

**Comment by shaomeng** [comment]
> Hmm. What version of Ubuntu is this? I'm guessing 22?

```
sam@Navada:~/Git/VAPOR/build$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**Pull request merged**
