### PR TITLE
Fix #1659 VDC that is missing higher resolution data still reports having it

### LINKED ISSUE #1659: VDC that is missing higher resolution data still reports having it
1. Create a VDC file
2. Remove the higher resolution data files (*.nc{1,2,3})
3. Open the dataset in vapor
4. Add a grid renderer

The `Data Fidelity` widget shows the higher resolutions as available. Selecting them results in the lower resolution being resampled onto a higher grid which can result in lower quality images than the lowest setting. For example:

Screen Shot 2019-06-10 at 5 29 49 PM

### PR DESCRIPTION
**Pull request by StasJ**
Fix #1659

Adds the ability to automatically grey out missing resolutions but without merging #2618, all resolutions are always returned as existing by the data mgr.

### CODE REVIEW

**Comment by shaomeng** [comment]
In my test, removing a file (e.g. ANGLE.nc3) doesn't trigger higher resolutions being grayed out?

**Review by sgpearse — APPROVED** [review]

**Comment by clyne** [comment]
@shaomeng needs to re-examine. Note, it's the levels-of-detail that may be missing, not resolution.

**Comment by shaomeng** [comment]
In my test, after removing a file (e.g., ANGLE.nc3), the highest level of detail, which is 1:1, is still shown as black and select-able. I believe it should be grayed out.

**Comment by StasJ** [comment]
> In my test, after removing a file (e.g., ANGLE.nc3), the highest level of detail, which is 1:1, is still shown as black and select-able. I believe it should be grayed out.

Main with the fix from #2618 had not been merged into this PR. It should work now.

**Comment by shaomeng** [comment]
It seems with the latest change, removing the highest numbered nc file (e.g. ANGLE.nc3) will gray out the highest refinement level, which is represented as a dimension, but not level of detail, which is represented as a ratio. Maybe @clyne can clarify which one is the correct value to gray out?

**Comment by clyne** [comment]
> It seems with the latest change, removing the highest numbered nc file (e.g. ANGLE.nc3) will gray out the highest refinement level, which is represented as a dimension, but not level of detail, which is represented as a ratio. Maybe @clyne can clarify which one is the correct value to gray out?

You are correct @shaomeng . It should be the highest LOD that is grayed out, not the Refinement Level.

**Comment by StasJ** [comment]
> > It seems with the latest change, removing the highest numbered nc file (e.g. ANGLE.nc3) will gray out the highest refinement level, which is represented as a dimension, but not level of detail, which is represented as a ratio. Maybe @clyne can clarify which one is the correct value to gray out?
> 
> You are correct @shaomeng . It should be the highest LOD that is grayed out, not the Refinement Level.

Good catch, thanks. I always mix up "Level of Detail" and "Refinement Level" or as they're named in the API: `lod` and `level` (#904).

It is now using the correct one.

**Review by shaomeng — APPROVED** [review]

**Pull request merged**
