### PR TITLE
Query parent classes for DOxygen docs

### PR DESCRIPTION
**Pull request by StasJ**
Fixes SliceParams documentation in #3168

### CODE REVIEW

**Comment by sgpearse** [comment]
@stasj this works, thank you for the fix.

One question: 
I don't see "tag" functions in the RenderParams base class help menu, such as GetSliceOffset().  Granted, it's only relevant for the slice/contour renderers.  But is there a reason why these functions aren't being documented in the RenderParams base class?

**Comment by StasJ** [comment]
> @StasJ this works, thank you for the fix.
> 
> One question: I don't see "tag" functions in the RenderParams base class help menu, such as GetSliceOffset(). Granted, it's only relevant for the slice/contour renderers. But is there a reason why these functions aren't being documented in the RenderParams base class?

Like you said, it's only relevant for the slice/contour renderers.

**Comment by sgpearse** [comment]
Can these be put in the RenderParams help menu?  This would be incredibly helpful for my understanding.

**Comment by StasJ** [comment]
> Can these tagged functions be put in the RenderParams help menu? This would be incredibly helpful for my understanding.

They can but that would result in, for example, the volume renderer having a NOP `GetSliceOffset()` method.

**Review by sgpearse — APPROVED** [review]

**Pull request merged**
