### PR TITLE
Issue 2708 - Smoke tests failing on 1D and 2D grids

### LINKED ISSUE #2708: Smoke tests failing on 1D and 2D grids
Our grid tests are failing on 1D and 2D grids due to assertions that grid dimension lengths need to be > 0.

To reproduce, check out main, build Vapor with test_apps=ON, and run the following grid tests:

~~- VAPOR/build/bin/testGrid -dims 1x1x1~~
~~- VAPOR/build/bin/testGrid -dims 1x8x8~~
~~- VAPOR/build/bin/testGrid -dims 8x1x8~~
~~- VAPOR/build/bin/testGrid -dims 8x8x1~~

- VAPOR/build/test_binaries/testGrid -dims 1x1x1
- VAPOR/build/test_binaries/testGrid -dims 1x8x8
- VAPOR/build/test_binaries/testGrid -dims 8x1x8
- VAPOR/build/test_binaries/testGrid -dims 8x8x1

### PR DESCRIPTION
**Pull request by clyne**
fixed #2708 

Wasn't checking for divide by zero

### CODE REVIEW

**Review by sgpearse — APPROVED** [review]

**Comment by clyne** [comment]
@shaomeng can you please give this a quick review?

**Comment by shaomeng** [comment]
> @shaomeng can you please give this a quick review?

Sorry for missing the review request.

A regular value divided by zero will produce an inf, which the PR tries to catch.
A zero divided by zero will produce an nan, which this PR does not catch. Then the question is, will that situation ever happen?

**Review by shaomeng — COMMENTED** [review]
See comment in the main thread.

**Comment by clyne** [comment]
> > @shaomeng can you please give this a quick review?
> 
> @clyne Sorry for missing the review request.
> 
> A regular value divided by zero will produce an inf, which the PR tries to catch. A zero divided by zero will produce an nan, which this PR does not catch. Then the question is, will that situation ever happen?

According to the reference [guide](https://en.cppreference.com/w/cpp/numeric/math/isfinite) std::isfinite:

_Determines if the given floating point number arg has finite value i.e. it is normal, subnormal or zero, but not infinite or NaN._

**Comment by shaomeng** [comment]
> > > @shaomeng can you please give this a quick review?
> > 
> > 
> > @clyne Sorry for missing the review request.
> > A regular value divided by zero will produce an inf, which the PR tries to catch. A zero divided by zero will produce an nan, which this PR does not catch. Then the question is, will that situation ever happen?
> 
> According to the reference [guide](https://en.cppreference.com/w/cpp/numeric/math/isfinite) std::isfinite:
> 
> _Determines if the given floating point number arg has finite value i.e. it is normal, subnormal or zero, but not infinite or NaN._

Looking good. Now I'm gonna approve it.

**Review by shaomeng — APPROVED** [review]

**Pull request merged**
