### PR TITLE
#2077 Change from slider to spinbox

### LINKED ISSUE #2077: Flow integration steps slider can easily lead to hang
The slider can easily allow the user to accidentally specify a very high value and then vapor will hang as it tries to compute the flow lines

### PR DESCRIPTION
**Pull request by StasJ**
Fix #2077

@sgpearse There are still a few things that need to be addressed with the VSpinBox:
- The changed signal is sometimes emitted multiple times for a single action with the same value.
- As you type, it will emit a value changed signal for every key press.
- Right-clicking on the widget causes the current value to be emitted as a changed value.

### CODE REVIEW

**Comment by sgpearse** [comment]
@stasj

> The changed signal is sometimes emitted multiple times for a single action with the same value.
Fixed, by adding a signal for the valueChanged and editingFinished events from the QSpinBox.

> As you type, it will emit a value changed signal for every key press.
This is still the behavior when you connect to the VIntSpinBox's ValueChanged signal, which can be used to change values interactively with the scroll-wheel.  I think the EditingFinished signal is what you may want, which will only emit on loss of focus, or return-press.

> Right-clicking on the widget causes the current value to be emitted as a changed value.
This was a weird one.  When right clicking on the widget, the QLineEdit within the QSpinBox would receive focus, then lose focus upon the drawing of the menu.  I've worked around it by having the VIntSpinBox track the current value and only emit EditingFinished if the value has changed.

**Comment by StasJ** [comment]
>> The changed signal is sometimes emitted multiple times for a single action with the same value.
>
> Fixed, by adding a signal for the valueChanged and editingFinished events from the QSpinBox.
> 
>> Right-clicking on the widget causes the current value to be emitted as a changed value.
>
> This was a weird one. When right clicking on the widget, the QLineEdit within the QSpinBox would receive focus, then lose focus upon the drawing of the menu. I've worked around it by having the VIntSpinBox track the current value and only emit EditingFinished if the value has changed.

Great, thanks!

> This is still the behavior when you connect to the VIntSpinBox's ValueChanged signal, which can be used to change values interactively with the scroll-wheel. I think the EditingFinished signal is what you may want, which will only emit on loss of focus, or return-press.

Should `VIntSpinbox` have multiple signals? I believe we decided that for consistency, the `VWidget` would take care of figuring out when it was appropriate to register a change and it would do that with the `ValueChanged` signal.

**Comment by sgpearse** [comment]
> Should VIntSpinbox have multiple signals? I believe we decided that for consistency, the VWidget would take care of figuring out when it was appropriate to register a change and it would do that with the ValueChanged signal.

This depends on whether we want to use a widget interactively.  ValueChanged will fire off as a user types a new number, or scrolls up/down on the spinbox.  EditingFinished will not fire as they type a new number - it will only fire when return is pressed, or the LineEdit loses focus.  I think we should anticipate the need to support both of these two use cases: the interactive and non-interactive modes.

**Comment by StasJ** [comment]
> > Should VIntSpinbox have multiple signals? I believe we decided that for consistency, the VWidget would take care of figuring out when it was appropriate to register a change and it would do that with the ValueChanged signal.
> 
> This depends on whether we want to use a widget interactively. ValueChanged will fire off as a user types a new number, or scrolls up/down on the spinbox. EditingFinished will not fire as they type a new number - it will only fire when return is pressed, or the LineEdit loses focus. I think we should anticipate the need to support both of these two use cases: the interactive and non-interactive modes.

That sounds good to me. Currently other widgets that support this have a `ValueChanged` signal and a `ValueChangedIntermediate` signal to account for this.

**Comment by sgpearse** [comment]
Got it.  I've changes the signal/slot names for consistency.

**Review by sgpearse — APPROVED** [review]

**Comment by sgpearse** [comment]
@clyne this PR is a collaboration between Stas and myself.  I think it's correct, but I'm going to ask for stas' review just to make sure we're all on the same page.

**Comment by clyne** [comment]
okey doke

**Comment by sgpearse** [comment]
Github can't find @StasJ in its reviewer selector right now.  Who knows why.  Stas, I think we're good here but could you let us know?

Screen Shot 2021-02-24 at 8 21 45 AM

**Comment by StasJ** [comment]
> Github can't find @StasJ in its reviewer selector right now. Who knows why. Stas, I think we're good here but could you let us know?

@sgpearse GitHub won't let me review my own PR but I approve your changes.

**Review by clyne — COMMENTED** [review]
The spin box introduced in the Flow/Seeding tab doesn't seem to work. Shouldn't it? If I load DUKU, and create a Flow renderer, changing the integration steps has no effect.

**Comment by sgpearse** [comment]
@clyne thanks for the catch John.  

There was a recent change regarding the ValueChangedIntermediate signal that introduced this bug.  I've been testing this on a different branch (#2622) and I missed this case.  It's fixed, and this widget now emits intermediate changes from the user.

interactiveStreamlines

**Review by clyne — APPROVED** [review]

**Pull request merged**
