### PR TITLE
Adding a test_app for FTLE calculation

### PR DESCRIPTION
**Pull request by ayenpure**
The PR contains all the files needed to calculate the FTLE field.
The README explains how to use this utility.

### CODE REVIEW

**Comment by clyne** [comment]
@ayenpure are you able to run the code with the changes you've made? I'm  getting the following:

CISL-UMATILLA[1062] ./build/bin/ftlecalc -datapath ~/Data/CM1/LeighOrf/directory -output /tmp/ftle.out -dimension 50x50x50 -duration 1.0 -length 0.1 -fieldname uinterp:vinterp:winterp
Advection for FTLE w/ : 
Data : /Users/clyne/Data/CM1/LeighOrf/directory
Field : uinterp | vinterp | winterp
Length : 0.1
Duration : 1
Dimensions : 50 | 50 | 50
nc_open(24Maycontrol.04001.000000.nc,) : No such file or directory
NetCDFSimple::Initialize(24Maycontrol.04001.000000.nc)
Failed to initialize netCDF data collection for reading
Failed to initialize data importer
Failed to intialize CF DataMGR


It looks like it's tripping over building the file list. I'd suggest that rather specifying a directory, and assuming that everything in the directory is a data file, allow the specification of files on the command line (without -datapath option)

**Comment by ayenpure** [comment]
But consider the example of the data we got from the FastEddy team where they have multiple hundred time steps.
How can we handle that case?
In case of FTLE we’re doing time-varying advection.

-Abhishek

**Comment by clyne** [comment]
If you are asking how to build the file list vector, try this:

    vector <string> files;
    for (int i=1; i<argc; i++) {
        files.push_back(argv[i]);
    }

If you are concerned about the number of files and and shell limits on command line length, I wouldn't think that would be an issue for this command; it only makes sense to have the FTLE calculation use a few time steps, correct? I'm fine with having -datapath as an alternate way of specifying the inputs, as long as it is working , and it doesn't currently seem to be :-)

**Comment by ayenpure** [comment]
Haha, definitely not the first!
I should quit s/w development not if I asked you that question.

Yes, my concern was the second.
I just figured the problem.
Since I replaced Boost with VAPOR’s utils I did not realize one thing.

FileUtils::ListFiles only lists file names and not complete paths.
I’ll fix the boo boo and and update the PR, and it should work for the command that you tried to run it with.

Sorry for that :)

-Abhishek

**Comment by clyne** [comment]
I thought you young guys might not know how to handle char** pointers in C++ :-)

I don't see the commit.... Was it pushed to the remote?

**Comment by ayenpure** [comment]
I just pushed it.
Can you verify it works for you?
It worked for my test data.

-Abhishek

**Comment by clyne** [comment]
Works now. Thanks.

**Pull request merged**
