### PR TITLE
render regression tests

### PR DESCRIPTION
**Pull request by StasJ**
- Runs tests concurrently. Tests can be configured for concurrency on a per-test basis
- Outputs rendered image, log containing stdout and stderr, and a session file for each test
- Supports globbing for file selection
- Allows specifying default renderer sets. For example can create a 2D renderer test suite, then you can specify to run the 2D test suite on a dataset. You can then also customize one of the renderers in the suite for that specific test, or add additional renderers.
- Supports Jinja2 templating
- Can specify various attributes timestep, isosurface value, etc.
- Test system monitors for crashes and will generate a crash report and create an output rendering that says the test failed.
- Test system keeps track of completed tests so tests can be interrupted between runs. System also keeps track of parameters used to run each test so if you change the test config, or the global config, it will recompute the parameters for each test and re-run only the tests affected by the change.
- Supports automatically generating tests for permutations of variable combos. I.e. if you specify 3 vars for the main var and 2 vars for the height var, it will run 6 tests for the various combos.
- Fully featured command-line tool: has full argument parsing with support for specifying configs to run, subsets of tests to run, dry runs, n jobs, and output location.

### CODE REVIEW

**Review by clyne — COMMENTED** [review]
@StasJ can you add some basic user documentation for the Python utilities? Example invocations and a description of the options would be great. These utils are really intended for developer purposes, so maybe just a markdown file in the directory with the utilities would be fine?

**Comment by clyne** [comment]
If the path to a data file in config.yaml is not valid the application will segfault: 

```
Warning: sysroot "/Applications/Xcode_12.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk" not found (ignoring for now).Vapor 3.6.1
Python 3.9.5 (/Users/clyne/tmp/miniconda/envs/vapor_new)
OpenGL 4.1 INTEL-16.5.2
 *** Break *** segmentation violation
[/Users/Shared/tmp/miniconda/envs/vapor_new/lib/python3.9/site-packages/cppyy_backend/lib/libCoreLegacy.6.20.04.so] CppyyLegacy::TUnixSystem::DispatchSignals(CppyyLegacy::ESignals) (no debug info)
[/usr/lib/system/libsystem_platform.dylib] _sigtramp (no debug info)
[<unknown binary>] (no debug info)
[/Users/Shared/tmp/miniconda/envs/vapor_new/lib/libvapi.dylib] Session::OpenDataset(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >) (no debug info)
```

To reproduce simply change 

`Source/WRF/DUKU/wrfout_d02_2007-04-01_00:00:00.nc 
`
in config.yaml

to 

`/Source/WRF/DUKU/wrfout_d02_2007-04-01_00:00:00.nc
`
and run run_config.py

**Comment by StasJ** [comment]
> If the path to a data file in config.yaml is not valid the application will segfault:
> 
> ```
> Warning: sysroot "/Applications/Xcode_12.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk" not found (ignoring for now).Vapor 3.6.1
> Python 3.9.5 (/Users/clyne/tmp/miniconda/envs/vapor_new)
> OpenGL 4.1 INTEL-16.5.2
>  *** Break *** segmentation violation
> [/Users/Shared/tmp/miniconda/envs/vapor_new/lib/python3.9/site-packages/cppyy_backend/lib/libCoreLegacy.6.20.04.so] CppyyLegacy::TUnixSystem::DispatchSignals(CppyyLegacy::ESignals) (no debug info)
> [/usr/lib/system/libsystem_platform.dylib] _sigtramp (no debug info)
> [<unknown binary>] (no debug info)
> [/Users/Shared/tmp/miniconda/envs/vapor_new/lib/libvapi.dylib] Session::OpenDataset(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >) (no debug info)
> ```
> 
> To reproduce simply change
> 
> `Source/WRF/DUKU/wrfout_d02_2007-04-01_00:00:00.nc ` in config.yaml
> 
> to
> 
> `/Source/WRF/DUKU/wrfout_d02_2007-04-01_00:00:00.nc ` and run run_config.py

In this case Vapor segfaults so we would expect the test to segfault. I've opened a PR to fix the crash here: #3198

**Comment by StasJ** [comment]
> > If the path to a data file in config.yaml is not valid the application will segfault:
> > ```
> > Warning: sysroot "/Applications/Xcode_12.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk" not found (ignoring for now).Vapor 3.6.1
> > Python 3.9.5 (/Users/clyne/tmp/miniconda/envs/vapor_new)
> > OpenGL 4.1 INTEL-16.5.2
> >  *** Break *** segmentation violation
> > [/Users/Shared/tmp/miniconda/envs/vapor_new/lib/python3.9/site-packages/cppyy_backend/lib/libCoreLegacy.6.20.04.so] CppyyLegacy::TUnixSystem::DispatchSignals(CppyyLegacy::ESignals) (no debug info)
> > [/usr/lib/system/libsystem_platform.dylib] _sigtramp (no debug info)
> > [<unknown binary>] (no debug info)
> > [/Users/Shared/tmp/miniconda/envs/vapor_new/lib/libvapi.dylib] Session::OpenDataset(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >) (no debug info)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > To reproduce simply change
> > `Source/WRF/DUKU/wrfout_d02_2007-04-01_00:00:00.nc ` in config.yaml
> > to
> > `/Source/WRF/DUKU/wrfout_d02_2007-04-01_00:00:00.nc ` and run run_config.py
> 
> In this case Vapor segfaults so we would expect the test to segfault. I've opened a PR to fix the crash here: #3198

One more comment, which will be mentioned in the readme, is that run_config.py is the primary user-facing script which then runs run_test.py in a sub process to gracefully handle segfaults. If you run run_test directly, it will crash if vapor crashes, while run_config won’t.

**Comment by clyne** [comment]
After building and installing on Casper using the instructions [here](https://docs.google.com/document/d/1RvbnJ_LbWvlUZzgjeutLQKwJV_M0blEHFSxsgSB7wRQ/edit?usp=sharing), I am able to run` run_config.py`. However, all of the output image files are empty. The log message is:

```
==============================

Vapor 3.6.1
Python 3.9.5 (/glade/u/home/clyne/.conda/envs/vapor_python)
OpenGL 4.6.0 NVIDIA 510.47.03
Dataset("cam5_1_amip_run2.cam2.h1.1979-01-01-00000.nc")
         2D Vars: CLDTOT, FLDS, FLDSC, FLNS, FLUT, FLUTC, FSDS, FSDSC, FSNS, FSNSC, FSNTOA, FSNTOAC, LHFLX, OMEGA500, OMEGA850, PRECC, PRECL, PRECSC, PRECSL, PRECT, PREC_pcw, PREC_zmc, PS, PSL, QREFHT, RHREFHT, SHFLX, SOLIN, T500, T850, TGCLDIWP, TGCLDLWP, TMQ, TREFHT, TREFHTMN, TREFHTMX, TREFMNAV, TREFMXAV
         3D Vars: CLDICE, CLDLIQ, CLOUD, CMFMC, CMFMCDZM, OMEGA, Q, RELHUM, T, U, V, Z3
<vapor.renderer.TwoDDataRenderer object at 0x2ac18073e340>
Wrong JPEG library version: library is 62, caller expects 90

=========== TEST COMPLETE ===========

```

Note that I'm able to run the example notebooks just fine.

**Comment by StasJ** [comment]
> After building and installing on Casper using the instructions [here](https://docs.google.com/document/d/1RvbnJ_LbWvlUZzgjeutLQKwJV_M0blEHFSxsgSB7wRQ/edit?usp=sharing), I am able to run` run_config.py`. However, all of the output image files are empty. The log message is:
> 
> ```
> ==============================
> 
> Vapor 3.6.1
> Python 3.9.5 (/glade/u/home/clyne/.conda/envs/vapor_python)
> OpenGL 4.6.0 NVIDIA 510.47.03
> Dataset("cam5_1_amip_run2.cam2.h1.1979-01-01-00000.nc")
>          2D Vars: CLDTOT, FLDS, FLDSC, FLNS, FLUT, FLUTC, FSDS, FSDSC, FSNS, FSNSC, FSNTOA, FSNTOAC, LHFLX, OMEGA500, OMEGA850, PRECC, PRECL, PRECSC, PRECSL, PRECT, PREC_pcw, PREC_zmc, PS, PSL, QREFHT, RHREFHT, SHFLX, SOLIN, T500, T850, TGCLDIWP, TGCLDLWP, TMQ, TREFHT, TREFHTMN, TREFHTMX, TREFMNAV, TREFMXAV
>          3D Vars: CLDICE, CLDLIQ, CLOUD, CMFMC, CMFMCDZM, OMEGA, Q, RELHUM, T, U, V, Z3
> <vapor.renderer.TwoDDataRenderer object at 0x2ac18073e340>
> Wrong JPEG library version: library is 62, caller expects 90
> 
> =========== TEST COMPLETE ===========
> ```
> 
> Note that I'm able to run the example notebooks just fine.

Thats odd, I'm not able to reproduce this. I tried on my mac, on a Casper login node, and on a Capser viz node. I don't know how that would happen since conda handles linking and our configuration specifies JPEG 9 as a runtime requirement. Maybe you could check your conda environment and see if the correct version of libjpeg is installed.

In any event, for now I've changed the output format to PNG since a lossless format makes more sense for regression testing anyway.

**Comment by sgpearse** [comment]
@stasJ Would you mind merging this branch with main, so that the python_api_ubuntu test can check the conda build?

**Comment by clyne** [comment]
>  Thats odd, I'm not able to reproduce this. I tried on my mac, on a Casper login node, and on a Capser viz node. I don't know how that would happen since conda handles linking and our configuration specifies JPEG 9 as a runtime requirement. Maybe you could check your conda environment and see if the correct version of libjpeg is installed.

> In any event, for now I've changed the output format to PNG since a lossless format makes more sense for regression testing anyway.

Switching to PNG solved the problem. However, I thought the conda build process was supposed to establish the correct build environment? Where should I check for "your conda environment and see if the correct version of libjpeg is installed."?

**Comment by clyne** [comment]
@StasJ I have run_config.py running fine now. Everything looks great except that all of the Image renderers are black screens. Are they working for you?

**Comment by StasJ** [comment]
> @StasJ Would you mind merging this branch with main, so that the python_api_ubuntu test can check the conda build?

@sgpearse Done.

---

> Switching to PNG solved the problem. However, I thought the conda build process was supposed to establish the correct build environment? Where should I check for "your conda environment and see if the correct version of libjpeg is installed."?

@clyne Yes, I thought so too. Run `conda list`

---

> @StasJ I have run_config.py running fine now. Everything looks great except that all of the Image renderers are black screens. Are they working for you?

By default the conda build is a debug build which does not include the map files. We need to host those somewhere so conda-build can download them. For now you can configure the build type and map file location in the meta.yaml config file.

**Comment by clyne** [comment]
> By default the conda build is a debug build which does not include the map files. We need to host those somewhere so conda-build can download them. For now you can configure the build type and map file location in the meta.yaml config file.

@StasJ, can you please give the precise syntax for this?

**Comment by StasJ** [comment]
> @StasJ, can you please give the precise syntax for this?

```
DEBUG_BUILD=false MAP_IMAGES_PATH="<path to folder containing map.tms>" conda build .
```

**Review by clyne — APPROVED** [review]

**Review by shaomeng — APPROVED** [review]
This looks cool; I'm sure it'll be very helpful in the future. Great job!

**Review by sgpearse — APPROVED** [review]
This worked wonderfully once I got it running.  However it's exposed a snag on our installers for Linux.  I think the problem can be dealt with after our first round of testing, so I'll just issue a new ticket with more details.

**Pull request merged**
