### PR TITLE
Reenable ospray isosurface renderer

### LINKED ISSUE #2450: OSPRay isosurfaces do not seem to work
I'm unable to render an isosurface using OSPRay with any data I've tested. The application hangs indefinitely much like it does with the volume renderer for some data: #2449. Unlike the volume renderer there is no way to control the isosurface sampling rate.

To reproduce:
1. Load Duku.nc
2. Enable the isosurface renderer with OSPRay selected as the rendering algorithm

### PR DESCRIPTION
**Pull request by StasJ**
I have done some experimenting with OSPRay 2.8 and it seems to be working.

Fix #2450

**Note** We need to upgrade our OSPRay third party libraries before accepting this PR.

### CODE REVIEW

**Comment by clyne** [comment]
Good deal. But we'll need to update all our builds to use OSPRay 2.8, correct? CC'ing @sgpearse for his input. Scott, is that doable?

**Comment by sgpearse** [comment]
> Scott, is that doable?

Sure, we've done it in the past.  @stasj, would you mind opening a ticket with a link to the new library and anything to be aware of?  Feel free to assign it to me.

**Comment by StasJ** [comment]
> > Scott, is that doable?
> 
> Sure, we've done it in the past. @StasJ, would you mind opening a ticket with a link to the new library and anything to be aware of? Feel free to assign it to me.

Thanks Scott. As far as I could tell from my testing, it seems to be a simple drop in replacement. Sure thing, I opened a ticket here: #2913

**Review by shaomeng — APPROVED** [review]

**Comment by sgpearse** [comment]
@clyne @stasj @shaomeng 

Hi guys, I'm going to go ahead and approve this.  You can find our new third party libraries [here](https://drive.google.com/drive/folders/0B0dQMtxB89M0Q2F2U3ZaQ2dVeWs?resourcekey=0-KjrYiMNi3FG-JnLKuDFupw&usp=sharing).

I'm still working out kinks in our build system that references these libraries.  A few issues have come up between CircleCI, Docker, and our Windows build, but you shouldn't have any problems linking to the files in the link above for your respective operating system.

**Review by sgpearse — APPROVED** [review]

**Comment by clyne** [comment]
> @clyne @StasJ @shaomeng
> 
> Hi guys, I'm going to go ahead and approve this. You can find our new third party libraries [here](https://drive.google.com/drive/folders/0B0dQMtxB89M0Q2F2U3ZaQ2dVeWs?resourcekey=0-KjrYiMNi3FG-JnLKuDFupw&usp=sharing).
> 
> I'm still working out kinks in our build system that references these libraries. A few issues have come up between CircleCI, Docker, and our Windows build, but you shouldn't have any problems linking to the files in the link above for your respective operating system.

@sgpearse just want to clarify that everyone should upgrade their 3rd party libs using the link above. Also, have all of our CI platforms been upgraded?

**Comment by sgpearse** [comment]
> @sgpearse just want to clarify that everyone should upgrade their 3rd party libs using the link above.

Yes, that's correct.

> Also, have all of our CI platforms been upgraded?

Not quite yet, there have been snags on all platforms and this is still in progress.  [These installers](https://app.circleci.com/pipelines/github/NCAR/VAPOR?branch=weekly) should verify this shortly.

**Comment by clyne** [comment]
@sgpearse  is still validating 3rd party libs with new version of ospray (2.8).

**Pull request merged**
