### PR TITLE
more refined bias controls

### PR DESCRIPTION
**Pull request by shaomeng**
This PR adjusts the flow seed bias control, so that 
1) The new control adjusts at 1/100 of the old refinement level, and
2) The new control exhibits the same adjustment range of the old control. 

Fix

56ea70a715fe2c1e01270a436c77f00587c9b364: [clangTidyOutput.txt](https://output.circle-artifacts.com/output/job/b579e3f2-4d9a-4f5c-b3a7-b1774c0a68dd/artifacts/0/tmp/clangTidyOutput.txt)

### CODE REVIEW

**Review by sgpearse — CHANGES_REQUESTED** [review]
Thanks Sam.  Could you make these slider ranges user-editable via the AllowUserRange(true) option?

This raises discussion outlined on #3166.  Should we allow PSliderEdits to have their ranges changed by the user by default?

**Comment by shaomeng** [comment]
> Thanks Sam. Could you make these slider ranges user-editable via the AllowUserRange(true) option?

Cool cool, I've added this option in [2fb7383](https://github.com/NCAR/VAPOR/pull/3163/commits/2fb7383e789541f4a325823aa5412e022747c40a).

**Review by sgpearse — APPROVED** [review]

**Comment by clyne** [comment]
@shaomeng please fix conflicts and then we can merge.

**Comment by shaomeng** [comment]
> @shaomeng please fix conflicts and then we can merge.

Conflict is resolved.

**Pull request merged**
